### ISSUE TITLE
Removing stick up cam

### ISSUE THREAD

**Issue by charmp121** [homespun/homebridge-platform-ring-video-doorbell#11]
How can I remove a stick up cam from homebridge? Installed a stickup cam which turned out to be faulty. Removed it from the ring app. When I received the new stick up cam - I installed it on the ring app. Now I have 2 different stick up cams show up - one updates correctly the other states no response. They have 2 different serial numbers and UUID's. How can I remove the incorrect and non working stick up cam? Any help would be greatly appreciated.

**Comment by mrose17** [comment]
hi. sorry for the delay in replying.

question: is the non-functional device removed from your ring account? if not, please remove it.

regardless, i need to check with a guru on something to ensure that i'm doing the right thing in the plugin. i will probably have a fix "soon"

thanks for your patience!

**Comment by mrose17** [comment]
@charmp121 - i believe if you install the latest version (and if you removed the non-functional device from your ring account), then the plugin should "do the right thing" (-;

thanks for reporting it!

**Comment by charmp121** [comment]
Hey, thanks for the reply. However the additional stick up cam is removed from my ring account. It still shows up in homebridge with a different UUID assigned to it. Is there any other way to remove it so it does not search or list it in homebridge?

**Comment by mrose17** [comment]
just checking: did you remove the old version of this plugin and re-install the latest version? if not, let's try that. if so, there is an "extreme" method to reset homebridge's persistent database.

1. stop homebridge
2. delete both the "accessories" and "persist" folders from `~/.homebridge/`

hopefully you don't have to do that...  good luck!
