### ISSUE TITLE
can't seem to get it to work! :(

### ISSUE THREAD

**Issue by silvermy** [homespun/homebridge-platform-ring-video-doorbell#12]
Apr 02 20:54:08 raspberrypi homebridge[14290]: /usr/local/lib/node_modules/homebridge/lib/api.js:118
Apr 02 20:54:08 raspberrypi homebridge[14290]: throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
Apr 02 20:54:08 raspberrypi homebridge[14290]: ^
Apr 02 20:54:08 raspberrypi homebridge[14290]: Error: The requested platform 'ring-video-doorbell' was not registered by any plugin.
Apr 02 20:54:08 raspberrypi homebridge[14290]: at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:118:13)
Apr 02 20:54:08 raspberrypi homebridge[14290]: at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:281:45)
Apr 02 20:54:08 raspberrypi homebridge[14290]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:77:36)
Apr 02 20:54:08 raspberrypi homebridge[14290]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Apr 02 20:54:08 raspberrypi homebridge[14290]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 02 20:54:08 raspberrypi homebridge[14290]: at Module._compile (module.js:409:26)
Apr 02 20:54:08 raspberrypi homebridge[14290]: at Object.Module._extensions..js (module.js:416:10)
Apr 02 20:54:08 raspberrypi homebridge[14290]: at Module.load (module.js:343:32)
Apr 02 20:54:08 raspberrypi homebridge[14290]: at Function.Module._load (module.js:300:12)
Apr 02 20:54:08 raspberrypi homebridge[14290]: at Function.Module.runMain (module.js:441:10)
Apr 02 20:54:08 raspberrypi homebridge[14290]: at startup (node.js:139:18)
Apr 02 20:54:08 raspberrypi homebridge[14290]: at node.js:974:3
Apr 02 20:54:08 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE

**Comment by mrose17** [comment]
try this:

        npm install -g homebridge-platform-ring-video-doorbell

if that doesn't complete without an error, let's figure out why!

**Comment by silvermy** [comment]
That is, basically, what I did, and it didn’t work, here is the output from a second attempt I just made:

# root@raspberrypi:~#  npm install --prefix /usr/local/lib/node_modules  homebridge-platform-ring-video-doorbell
> arp-a@0.5.1 install /usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/arp-a
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/arp-a/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/arp-a/build'
  SOLINK_MODULE(target) Release/obj.target/macos.node
  COPY Release/macos.node
make: Leaving directory '/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/arp-a/build'

> socketwatcher@0.3.0 install /usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2/node_modules/socketwatcher
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2/node_modules/socketwatcher/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2/node_modules/socketwatcher/build'

> pcap2@3.0.4 install /usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2/build'
  CXX(target) Release/obj.target/pcap_binding/src/pcap_binding.o
  CXX(target) Release/obj.target/pcap_binding/src/pcap_session.o
  SOLINK_MODULE(target) Release/obj.target/pcap_binding.node
  COPY Release/pcap_binding.node
make: Leaving directory '/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2/build'
homebridge-platform-ring-video-doorbell@0.3.0 ../usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell
├── hap-nodejs-community-types@0.2.0-alpha0
├── underscore@1.8.3
└── homespun-discovery@0.1.21 (pluralize@3.0.0, uuid@3.0.0, snmp-native@1.0.18, multicast-dns@6.1.1, bonjour@3.5.0, glob@7.1.1, xml2js@0.2.8, arp-a@0.5.1, pcap2@3.0.4)

One thing,  based on your README and http://stackoverflow.com/questions/5779784/pcap-h-header-file-problem <http://stackoverflow.com/questions/5779784/pcap-h-header-file-problem> - I executed the command # apt-get install libpcap0.8-dev and then re-did the ‘npm install’ in order for the latter to succeed.

Here is the config I added to the platforms section in the config (email and password masked):

{ 
  "platform"  : "ring-video-doorbell",
  "name"      : "Doorbell",
  "username"  : “***@***.com",
  "password"  : "***"
}

And here is the ‘journaldctl’ output after I ‘systemctl restart homebridge’ (including output for other plugins I have, I have no idea why chromecast is even showing up - it is not in the config - but it doesn’t appear to cause any damage):

Apr 05 18:50:01 raspberrypi homebridge[29644]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Apr 05 18:50:01 raspberrypi node[29644]: *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
Apr 05 18:50:01 raspberrypi node[29644]: *** WARNING *** Please fix your application to use the native API of Avahi!
Apr 05 18:50:01 raspberrypi node[29644]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Apr 05 18:50:01 raspberrypi node[29644]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Apr 05 18:50:01 raspberrypi node[29644]: *** WARNING *** Please fix your application to use the native API of Avahi!
Apr 05 18:50:01 raspberrypi node[29644]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Apr 05 18:50:01 raspberrypi homebridge[29644]: *** WARNING *** Please fix your application to use the native API of Avahi!
Apr 05 18:50:01 raspberrypi homebridge[29644]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Apr 05 18:50:01 raspberrypi homebridge[29644]: *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Apr 05 18:50:01 raspberrypi homebridge[29644]: *** WARNING *** Please fix your application to use the native API of Avahi!
Apr 05 18:50:01 raspberrypi homebridge[29644]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Apr 05 18:50:06 raspberrypi homebridge[29644]: [4/5/2017, 6:50:06 PM] Loaded plugin: homebridge-gpio
Apr 05 18:50:07 raspberrypi homebridge[29644]: [4/5/2017, 6:50:07 PM] Registering accessory 'homebridge-gpio.GPIO'
Apr 05 18:50:07 raspberrypi homebridge[29644]: [4/5/2017, 6:50:07 PM] ---
Apr 05 18:50:07 raspberrypi homebridge[29644]: [4/5/2017, 6:50:07 PM] Loaded plugin: homebridge-gpio-dooralarm
Apr 05 18:50:07 raspberrypi homebridge[29644]: [4/5/2017, 6:50:07 PM] Registering accessory 'homebridge-gpio-dooralarm.RaspPiGPIODoorAlarm'
Apr 05 18:50:07 raspberrypi homebridge[29644]: [4/5/2017, 6:50:07 PM] ---
Apr 05 18:50:17 raspberrypi homebridge[29644]: [4/5/2017, 6:50:17 PM] Loaded plugin: homebridge-nest
Apr 05 18:50:17 raspberrypi homebridge[29644]: [4/5/2017, 6:50:17 PM] Registering platform 'homebridge-nest.Nest'
Apr 05 18:50:17 raspberrypi homebridge[29644]: [4/5/2017, 6:50:17 PM] ---
Apr 05 18:50:24 raspberrypi homebridge[29644]: [4/5/2017, 6:50:24 PM] Loaded plugin: homebridge-platform-wemo
Apr 05 18:50:24 raspberrypi homebridge[29644]: [4/5/2017, 6:50:24 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
Apr 05 18:50:24 raspberrypi homebridge[29644]: [4/5/2017, 6:50:24 PM] ---
Apr 05 18:50:24 raspberrypi homebridge[29644]: [4/5/2017, 6:50:24 PM] ====================
Apr 05 18:50:24 raspberrypi homebridge[29644]: [4/5/2017, 6:50:24 PM] ERROR LOADING PLUGIN homebridge-plugin-chromecast:
Apr 05 18:50:24 raspberrypi homebridge[29644]: [4/5/2017, 6:50:24 PM] SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
Apr 05 18:50:24 raspberrypi homebridge[29644]: at exports.runInThisContext (vm.js:53:16)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Module._compile (module.js:373:25)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Object.Module._extensions..js (module.js:416:10)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Module.load (module.js:343:32)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Function.Module._load (module.js:300:12)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Module.require (module.js:353:17)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at require (internal/module.js:12:17)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:65:22)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:129:14)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Array.forEach (native)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:125:22)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:48:24)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Module._compile (module.js:409:26)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Object.Module._extensions..js (module.js:416:10)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Module.load (module.js:343:32)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Function.Module._load (module.js:300:12)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at Function.Module.runMain (module.js:441:10)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at startup (node.js:139:18)
Apr 05 18:50:24 raspberrypi homebridge[29644]: at node.js:974:3
Apr 05 18:50:24 raspberrypi homebridge[29644]: [4/5/2017, 6:50:24 PM] ====================
Apr 05 18:50:24 raspberrypi homebridge[29644]: [4/5/2017, 6:50:24 PM] Loaded plugin: homebridge-rasppi-gpio-garagedoor
Apr 05 18:50:24 raspberrypi homebridge[29644]: [4/5/2017, 6:50:24 PM] Registering accessory 'homebridge-rasppi-gpio-garagedoor.RaspPiGPIOGarageDoor'
Apr 05 18:50:24 raspberrypi homebridge[29644]: [4/5/2017, 6:50:24 PM] ---
Apr 05 18:50:29 raspberrypi homebridge[29644]: [4/5/2017, 6:50:29 PM] Loaded plugin: homebridge-zway
Apr 05 18:50:29 raspberrypi homebridge[29644]: [4/5/2017, 6:50:29 PM] Registering accessory 'homebridge-zway.ZWayServer'
Apr 05 18:50:29 raspberrypi homebridge[29644]: [4/5/2017, 6:50:29 PM] Registering platform 'homebridge-zway.ZWayServer'
Apr 05 18:50:29 raspberrypi homebridge[29644]: [4/5/2017, 6:50:29 PM] ---
Apr 05 18:50:29 raspberrypi homebridge[29644]: [4/5/2017, 6:50:29 PM] Loaded config.json with 2 accessories and 2 platforms.
Apr 05 18:50:29 raspberrypi homebridge[29644]: [4/5/2017, 6:50:29 PM] ---
Apr 05 18:50:29 raspberrypi homebridge[29644]: [4/5/2017, 6:50:29 PM] Loading 2 platforms...
Apr 05 18:50:29 raspberrypi homebridge[29644]: [4/5/2017, 6:50:29 PM] Initializing Nest platform...
Apr 05 18:50:29 raspberrypi homebridge[29644]: [4/5/2017, 6:50:29 PM] Fetching Nest devices.
Apr 05 18:50:30 raspberrypi homebridge[29644]: /usr/local/lib/node_modules/homebridge/lib/api.js:118
Apr 05 18:50:30 raspberrypi homebridge[29644]: throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
Apr 05 18:50:30 raspberrypi homebridge[29644]: ^
Apr 05 18:50:30 raspberrypi homebridge[29644]: Error: The requested platform 'ring-video-doorbell' was not registered by any plugin.
Apr 05 18:50:30 raspberrypi homebridge[29644]: at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:118:13)
Apr 05 18:50:30 raspberrypi homebridge[29644]: at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:281:45)
Apr 05 18:50:30 raspberrypi homebridge[29644]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:77:36)
Apr 05 18:50:30 raspberrypi homebridge[29644]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Apr 05 18:50:30 raspberrypi homebridge[29644]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 05 18:50:30 raspberrypi homebridge[29644]: at Module._compile (module.js:409:26)
Apr 05 18:50:30 raspberrypi homebridge[29644]: at Object.Module._extensions..js (module.js:416:10)
Apr 05 18:50:30 raspberrypi homebridge[29644]: at Module.load (module.js:343:32)
Apr 05 18:50:30 raspberrypi homebridge[29644]: at Function.Module._load (module.js:300:12)
Apr 05 18:50:30 raspberrypi homebridge[29644]: at Function.Module.runMain (module.js:441:10)
Apr 05 18:50:30 raspberrypi homebridge[29644]: at startup (node.js:139:18)
Apr 05 18:50:30 raspberrypi homebridge[29644]: at node.js:974:3
Apr 05 18:50:30 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Apr 05 18:50:30 raspberrypi systemd[1]: Unit homebridge.service entered failed state.


THANK YOU for all your help with this!  - Yossie

**Comment by mrose17** [comment]
thanks for your patience, please run these commands on your system and cut-and-paste the output:

    % node --version
    % npm --version
    % ls /usr/local/lib/node_modules

also, somewhere on your system is the `node-gyp` binary, find it and run it, e.g.,

    % /usr/local/lib/node_modules/npmbin/node-gyp-bin/node-gyp --version

thanks!

**Comment by mrose17** [comment]
one other thing, try running this command to see if it works:

        npm install --unsafe-perm --prefix /usr/local/lib/node_modules  homebridge-platform-ring-video-doorbell

good luck!

**Comment by silvermy** [comment]
root@raspberrypi:~# node --version
v4.6.0

root@raspberrypi:~# npm --version
2.15.9

root@raspberrypi:~# ls /usr/local/lib/node_modules
etc			   homebridge-nest		      node-gyp
hap-nodejs		   homebridge-platform-wemo	      node_modules
homebridge		   homebridge-plugin-chromecast       npm
homebridge-gpio		   homebridge-rasppi-gpio-garagedoor
homebridge-gpio-dooralarm  homebridge-zway

root@raspberrypi:~# /usr/local/lib/node_modules/npm/bin/node-gyp-bin/node-gyp --version
v3.4.0

**Comment by silvermy** [comment]
I ran this command.  It succeeded.

I changed the config to use ring and restarted it, I got the same errors as before

Apr 06 23:02:37 raspberrypi homebridge[19737]: /usr/local/lib/node_modules/homebridge/lib/api.js:118
Apr 06 23:02:37 raspberrypi homebridge[19737]: throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
Apr 06 23:02:37 raspberrypi homebridge[19737]: ^
Apr 06 23:02:37 raspberrypi homebridge[19737]: Error: The requested platform 'ring-video-doorbell' was not registered by any plugin.
Apr 06 23:02:37 raspberrypi homebridge[19737]: at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:118:13)

**Comment by mrose17** [comment]
what we need to determine is why the `ring-video-doorbell" plugin isn't installing properly.

please re-run

        npm install --unsafe-perm --prefix /usr/local/lib/node_modules  homebridge-platform-ring-video-doorbell

and include all the output... thanks!

**Comment by silvermy** [comment]
root@raspberrypi:~# npm install --unsafe-perm --prefix /usr/local/lib/node_modules  homebridge-platform-ring-video-doorbell
 
> arp-a@0.5.1 install /usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/arp-a
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/arp-a/build'
  SOLINK_MODULE(target) Release/obj.target/macos.node
  COPY Release/macos.node
make: Leaving directory '/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/arp-a/build'

> socketwatcher@0.3.0 install /usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2/node_modules/socketwatcher/build'

> pcap2@3.0.4 install /usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2/build'
  CXX(target) Release/obj.target/pcap_binding/src/pcap_binding.o
  CXX(target) Release/obj.target/pcap_binding/src/pcap_session.o
  SOLINK_MODULE(target) Release/obj.target/pcap_binding.node
  COPY Release/pcap_binding.node
make: Leaving directory '/usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell/node_modules/homespun-discovery/node_modules/pcap2/build'
homebridge-platform-ring-video-doorbell@0.3.0 ../usr/local/lib/node_modules/node_modules/homebridge-platform-ring-video-doorbell
├── hap-nodejs-community-types@0.2.0-alpha0
├── underscore@1.8.3
└── homespun-discovery@0.1.21 (pluralize@3.0.0, uuid@3.0.0, snmp-native@1.0.18, bonjour@3.5.0, multicast-dns@6.1.1, xml2js@0.2.8, glob@7.1.1, arp-a@0.5.1, pcap2@3.0.4)

**Comment by mrose17** [comment]
well, that looks like a clean install to me...  the thing that looks "odd" to me is the two occurrences of `node_modules` in the output above.  try this:

      npm install --unsafe-perm --prefix /usr/local/lib homebridge-platform-ring-video-doorbell

maybe that will work. good luck!

**Comment by silvermy** [comment]
Now there is a version mismatch?

Apr 11 15:02:00 raspberrypi homebridge[31233]: [4/11/2017, 3:02:00 PM] ====================
Apr 11 15:02:00 raspberrypi homebridge[31233]: [4/11/2017, 3:02:00 PM] ERROR LOADING PLUGIN homebridge-platform-ring-video-doorbell:
Apr 11 15:02:00 raspberrypi homebridge[31233]: [4/11/2017, 3:02:00 PM] Error: Plugin /usr/local/lib/node_modules/homebridge-platform-ring-video-doorbell requires a HomeBridge version of >=0.4.16 which does not satisfy the current HomeBridge version of 0.4.6. You may need to upgrade your installation of HomeBridge.
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:129:14)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Array.forEach (native)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:125:22)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:48:24)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Module._compile (module.js:409:26)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Object.Module._extensions..js (module.js:416:10)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Module.load (module.js:343:32)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Function.Module._load (module.js:300:12)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Function.Module.runMain (module.js:441:10)
Apr 11 15:02:01 raspberrypi homebridge[31233]: at startup (node.js:139:18)
Apr 11 15:02:01 raspberrypi homebridge[31233]: at node.js:974:3

**Comment by mrose17** [comment]
i'm afraid so, you need to upgrade homebridge to either 0.4.16 (what the ring plugin requires) or 0.4.17 (which is the latest).../mtr
          
            
            On Apr 11 2017, at 8:04 am, silvermy <notifications@github.com> wrote:
            
            
              Now there is a version mismatch?

Apr 11 15:02:00 raspberrypi homebridge[31233]: [4/11/2017, 3:02:00 PM] ====================
Apr 11 15:02:00 raspberrypi homebridge[31233]: [4/11/2017, 3:02:00 PM] ERROR LOADING PLUGIN homebridge-platform-ring-video-doorbell:
Apr 11 15:02:00 raspberrypi homebridge[31233]: [4/11/2017, 3:02:00 PM] Error: Plugin /usr/local/lib/node_modules/homebridge-platform-ring-video-doorbell requires a HomeBridge version of >=0.4.16 which does not satisfy the current HomeBridge version of 0.4.6. You may need to upgrade your installation of HomeBridge.
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:129:14)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Array.forEach (native)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:125:22)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:48:24)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Module._compile (module.js:409:26)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Object.Module._extensions..js (module.js:416:10)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Module.load (module.js:343:32)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Function.Module._load (module.js:300:12)
Apr 11 15:02:00 raspberrypi homebridge[31233]: at Function.Module.runMain (module.js:441:10)
Apr 11 15:02:01 raspberrypi homebridge[31233]: at startup (node.js:139:18)
Apr 11 15:02:01 raspberrypi homebridge[31233]: at node.js:974:3

**Comment by silvermy** [comment]
OK, I will do that.

I would like some advice - I’d prefer to keep current functionality over new - so, if the upgrade fails for whatever reason ,I’d like to revert.  How can I backup the current state?  tar.gz /usr/local?  Will that do the job?

Thanks - Yossie

**Comment by mrose17** [comment]
you can use tar to backup all of /usr/local, but all you really need to do is backup /usr/local/lib/node_modules/homebridge ... good luck!

**Comment by silvermy** [comment]
OK!

I executed:

npm install --unsafe-perm --prefix /usr/local/lib homebridge

.. and after a lengthy intsall/upgrade process, and the necessary change to the config, the ring doorbell is now showing up.

I still can’t see how to enable motion detection and/or setup snapshot being forward to IOS device.  Maybe you can point at a tutorial?

Either way, THANK YOU FOR YOUR ASSIST!

Cheers - Y

**Comment by mrose17** [comment]
great! enjoy!
