### ISSUE TITLE
Camera ffmpeg integration

### ISSUE THREAD

**Issue by kapps7** [homespun/homebridge-platform-ring-video-doorbell#13]
Hi I checked the comments regarding the closed issue here:https://github.com/homespun/homebridge-platform-ring-video-doorbell/issues/6

I am trying to integrate the camera feed but without success
I can't find any rtsp support for Ring & I tried both the Doorbird full and basic settings as well as the generic RTSP url without success
Appreciate any help

**Comment by macjeff** [comment]
yes can you give us some more info on how to access the camera?

**Comment by rjmcfadd** [comment]
Does anyone know how to get the camera integration to work like @barkerja said? Thanks!

**Comment by tbelcher** [comment]
Same question here - can anyone provide an example of a working config file?

Thanks,

Tim

**Comment by RodBruno** [comment]
As for what  @barkerja "suggested"...reading the original thread, this person never mentioned that the ring camera would work with Camera ffmpeg. His point is that, if you install a "camera"(any other camera working with ffmpeg plugin for example) and on the homekit app add to the same "room"(Group), the camera would turn on once the ring motion is activated for example. 

So the camera integration text in the readme file as found today is misleading :

"Camera Integration

The current version of this plugin doesn't handle the camera available in the Ring Video doorbell; however, as noted by @barkerja, you can use the camera plugin, and place both accessories in the same "room". HomeKit manage the two accessories as one "seamless" device."

**Comment by jocamero** [comment]
Thanks for the clarification!

**Comment by jer78** [comment]
FYI...there’s work being done over here. 

https://github.com/tchellomello/python-ring-doorbell/issues/23

Maybe someone will be able to eventually figure it out. It doesn’t look like the official HomeKit integration is coming anytime soon according to the comments on the Ring blog.

**Comment by cameronf87** [comment]
Any updates on this? The API now supports live streaming: http://www.kidder.io/2017/07/04/ring-doorbell-api/
