### ISSUE TITLE
Multiple Homebridge

### ISSUE THREAD

**Issue by KardelSniper** [homespun/homebridge-platform-ring-video-doorbell#14]
Hi there,
I recently encountered this problem when trying to run a second homebridge instance - in the second homebridge, I created this new config.json that doesn't contain any information about ring, and I made sure the persist and accessories folders are empty. But when I started this second homebridge, the plugin constantly reported error, like username: undefined, _roundTrip error: HTTP response 401. Seems like the plugin still tried to run even there was no configuration. Is there anyway to fix this? Thank you!

**Comment by mrose17** [comment]
thanks for reporting this.. i have investigated and pushed a new version, 0.3.1, which fixes the problem.

good luck!

**Comment by KardelSniper** [comment]
Yep, working like a charm now! Thank you so much for the update, totally awesome!
