### ISSUE TITLE
User "root" does not have permission to access the dev dir

### ISSUE THREAD

**Issue by chasebmcvicker** [homespun/homebridge-platform-ring-video-doorbell#15]
Ran into the error message you said might happen.  tried to install the libcap-dev as outlined but still go the same error string when i tried to reinstall the plugin.  Any ideas?

**Comment by mrose17** [comment]
i believe the easiest fix is to include `--unsafe-perm` whenever you run `npm`, e.g.,

     npm install --unsafe-perm ...

good luck!

**Comment by mophl1** [comment]
I'm also having this problem with...

**Comment by nabdo** [comment]
anyone else still having an issue, even with --unsafe-perm

**Comment by CanonCan** [comment]
I am having issues with all three suggested ways--Using Homebridge for Docker on Unraid


here is the output of errors

root@<Server>:/# sudo npm install --unsafe-perm -g homebridge-platform-ring-video-doorbell

> arp-a@0.5.1 install /usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/arp-a
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/arp-a/build'
  SOLINK_MODULE(target) Release/obj.target/macos.node
  COPY Release/macos.node
make: Leaving directory `/usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/arp-a/build'

> socketwatcher@0.3.0 install /usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory `/usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/socketwatcher/build'

> pcap2@3.0.4 install /usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap2
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap2/build'
  CXX(target) Release/obj.target/pcap_binding/src/pcap_binding.o
../src/pcap_binding.cc:2:23: fatal error: pcap/pcap.h: No such file or directory
 #include <pcap/pcap.h>
                       ^
compilation terminated.
make: *** [Release/obj.target/pcap_binding/src/pcap_binding.o] Error 1
make: Leaving directory `/usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.12.10-unRAID
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap2
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
/usr/lib
└── (empty)

npm ERR! Linux 4.12.10-unRAID
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--unsafe-perm" "-g" "homebridge-platform-ring-video-doorbell"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! pcap2@3.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcap2@3.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pcap2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pcap2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pcap2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
npm ERR! code 1

**Comment by mrose17** [comment]
i have seen that before when node/homebridge is installed by root and then other packages can't be installed. i don't know what causes it, unfortunately. perhaps someone at https://homebridgeteam.slack.com/ can help?
