### ISSUE TITLE
Installation failed: npm ERR! code 128

### ISSUE THREAD

**Issue by tonytien** [homespun/homebridge-platform-ring-video-doorbell#17]
I tried to install this npm plugin using `sudo npm install -g homebridge-platform-ring-video-doorbell`, but I've been unable to even get past that step. After I enter that command, I get the following output:

```
pi@raspberrypi:~ $ sudo npm install -g homebridge-platform-ring-video-doorbell
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-c70ce845
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-c70ce845': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-10T06_08_36_754Z-debug.log
```

Here are the contents of that `/root/.npm/_logs/2017-07-10T06_08_36_754Z-debug.log` file:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-platform-ring-video-doorbell' ]
2 info using npm@5.1.0
3 info using node@v8.1.3
4 verbose npm-session 5221f50ad64adcd9
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-platform-ring-video-doorbell 767ms (from cache)
8 silly pacote tag manifest for homebridge-platform-ring-video-doorbell@latest fetched in 941ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule homebridge-platform-ring-video-doorbell@0.4.0 checking installable status
14 http fetch GET 304 https://registry.npmjs.org/underscore 246ms (from cache)
15 silly pacote version manifest for underscore@1.8.3 fetched in 256ms
16 silly resolveWithNewModule underscore@1.8.3 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/doorbot 414ms (from cache)
18 silly pacote version manifest for doorbot@1.0.0 fetched in 422ms
19 silly resolveWithNewModule doorbot@1.0.0 checking installable status
20 http fetch GET 304 https://registry.npmjs.org/homespun-discovery 489ms (from cache)
21 silly pacote version manifest for homespun-discovery@0.1.21 fetched in 497ms
22 silly resolveWithNewModule homespun-discovery@0.1.21 checking installable status
23 silly fetchPackageMetaData error for hap-nodejs-community-types@git+https://github.com/homespun/hap-nodejs-community-types.git Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/homespun/hap-nodejs-community-$
23 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-839b78a5': Permission denied
24 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-839b78a5
24 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-839b78a5': Permission denied
24 verbose stack
24 verbose stack     at ChildProcess.exithandler (child_process.js:270:12)
24 verbose stack     at emitTwo (events.js:125:13)
24 verbose stack     at ChildProcess.emit (events.js:213:7)
24 verbose stack     at maybeClose (internal/child_process.js:897:16)
24 verbose stack     at Socket.stream.socket.on (internal/child_process.js:340:11)
24 verbose stack     at emitOne (events.js:115:13)
24 verbose stack     at Socket.emit (events.js:210:7)
24 verbose stack     at Pipe._handle.close [as _onclose] (net.js:549:12)
25 verbose cwd /home/pi
26 verbose Linux 4.9.35-v7+
27 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge-platform-ring-video-doorbell"
28 verbose node v8.1.3
29 verbose npm  v5.1.0
30 error code 128
31 error Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-839b78a5
31 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-839b78a5': Permission denied
32 verbose exit [ 1, true ]
```

**Comment by mrose17** [comment]
take a look at https://github.com/homespun/homebridge-platform-ring-video-doorbell/issues/2

you may find a command like `sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell` that may help

**Comment by tonytien** [comment]
I tried running `apt-get install libpcap-dev,` as recommended by the second post on #2. I had to run it as root, which got me this:

```
pi@raspberrypi:~ $ sudo apt-get install libpcap-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libpcap-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  libc-ares2 libv8-3.14.5
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I then tried running `sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell`, which yielded this:

```
pi@raspberrypi:~ $ sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-f98a4f0c
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-f98a4f0c': Permission denied
npm ERR! 


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.1.0 → 5.2.0    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-12T05_11_49_904Z-debug.log
```

So before continuing, I decided to upgrade npm using `sudo npm i -g npm`, after which I ran `sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell` again. The results:

```
pi@raspberrypi:~ $ sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-0a285a4c
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-0a285a4c': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-12T05_13_55_508Z-debug.log
```

And the new log file, `/root/.npm/_logs/2017-07-12T05_13_55_508Z-debug.log`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '--unsafe-perm',
1 verbose cli   'homebridge-platform-ring-video-doorbell' ]
2 info using npm@5.2.0
3 info using node@v8.1.3
4 verbose npm-session 62611596b5785198
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/homebridge-platform-ring-video-doorbell 116ms (from cache)
8 silly pacote tag manifest for homebridge-platform-ring-video-doorbell@latest fetched in 288ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule homebridge-platform-ring-video-doorbell@0.4.0 checking installable status
14 http fetch GET 200 https://registry.npmjs.org/doorbot 183ms (from cache)
15 http fetch GET 200 https://registry.npmjs.org/homespun-discovery 160ms (from cache)
16 http fetch GET 200 https://registry.npmjs.org/underscore 164ms (from cache)
17 silly pacote version manifest for doorbot@1.0.0 fetched in 206ms
18 silly resolveWithNewModule doorbot@1.0.0 checking installable status
19 silly pacote version manifest for homespun-discovery@0.1.21 fetched in 182ms
20 silly resolveWithNewModule homespun-discovery@0.1.21 checking installable status
21 silly pacote version manifest for underscore@1.8.3 fetched in 184ms
22 silly resolveWithNewModule underscore@1.8.3 checking installable status
23 silly fetchPackageMetaData error for hap-nodejs-community-types@git+https://github.com/homespun/hap-nodejs-community-types.git Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/homespun/hap-nodejs-community-$
23 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-0a285a4c': Permission denied
24 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-0a285a4c
24 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-0a285a4c': Permission denied
24 verbose stack
24 verbose stack     at ChildProcess.exithandler (child_process.js:270:12)
24 verbose stack     at emitTwo (events.js:125:13)
24 verbose stack     at ChildProcess.emit (events.js:213:7)
24 verbose stack     at maybeClose (internal/child_process.js:897:16)
24 verbose stack     at Socket.stream.socket.on (internal/child_process.js:340:11)
24 verbose stack     at emitOne (events.js:115:13)
24 verbose stack     at Socket.emit (events.js:210:7)
24 verbose stack     at Pipe._handle.close [as _onclose] (net.js:549:12)
25 verbose cwd /home/pi
26 verbose Linux 4.9.35-v7+
27 verbose argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-platform-ring-video-doorbell"
28 verbose node v8.1.3
29 verbose npm  v5.2.0
30 error code 128
31 error Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-0a285a4c
31 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-0a285a4c': Permission denied
32 verbose exit [ 1, true ]
```

**Comment by craigdent** [comment]
im getting the same error trying to install this plugin... any fixes?

**Comment by mrose17** [comment]
@craigdent - take a look at https://github.com/homespun/homebridge-platform-ring-video-doorbell/issues/2

you may find a command like `sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell` that may help

**Comment by geofbuck** [comment]
I am having the same problem in mac os x. It worked before, the new version is corrupt and does not load properly from npm. I get this " code 1
npm ERR! Command failed: /usr/local/bin/git clone --depth=1 -q -b master https://github.com/homespun/hap-nodejs-community-types.git /Users/pms/.npm/_cacache/tmp/git-clone-842e5520"

**Comment by geofbuck** [comment]
Using the above command you suggested also fails with same error.

**Comment by geofbuck** [comment]
It is definitely a build error in the update.

**Comment by craigdent** [comment]
Yeah I've tried the unsafe-perm

It's definitely a build error

Can it be recompiled and uploaded for us all to get

**Comment by mrose17** [comment]
here is what i just ran:

        npm -g install homebridge homebridge-platform-ring-video-doorbell

cf., https://gist.github.com/mrose17/14c1697a799da195b921f3d4304d99e8

**Comment by craigdent** [comment]
Still getting same error

**Comment by geofbuck** [comment]
I don't profess to know very much about node.js but I found that the problem is a permissions issue. I messed around with the permissions on the usr folder so that the plugin would install, then did a disk utility repair to fix permissions correctly. @craigdent make sure homebridge is up to date. I uninstalled it and reinstalled it using sudo command for everything.

**Comment by CanonCan** [comment]
@mrose17 

could we get an estimated time for a new Build? this one is definitely got dependency issue and packaging issues.


root@MyServer:/# sudo npm install -g --unsafe-perm homebridge-platform-ring-video-do              orbell

> arp-a@0.5.1 install /usr/lib/node_modules/homebridge-platform-ring-video-doorb              ell/node_modules/arp-a
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/homebridge-platform-ring-video-d              oorbell/node_modules/arp-a/build'
  SOLINK_MODULE(target) Release/obj.target/macos.node
  COPY Release/macos.node
make: Leaving directory `/usr/lib/node_modules/homebridge-platform-ring-video-do              orbell/node_modules/arp-a/build'

> socketwatcher@0.3.0 install /usr/lib/node_modules/homebridge-platform-ring-vid              eo-doorbell/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/homebridge-platform-ring-video-d              oorbell/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory `/usr/lib/node_modules/homebridge-platform-ring-video-do              orbell/node_modules/socketwatcher/build'

> pcap2@3.0.4 install /usr/lib/node_modules/homebridge-platform-ring-video-doorb              ell/node_modules/pcap2
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/homebridge-platform-ring-video-d              oorbell/node_modules/pcap2/build'
  CXX(target) Release/obj.target/pcap_binding/src/pcap_binding.o
../src/pcap_binding.cc:2:23: fatal error: pcap/pcap.h: No such file or directory
 #include <pcap/pcap.h>
                       ^
compilation terminated.
make: *** [Release/obj.target/pcap_binding/src/pcap_binding.o] Error 1
make: Leaving directory `/usr/lib/node_modules/homebridge-platform-ring-video-do              orbell/node_modules/pcap2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_module              s/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces              s.js:204:12)
gyp ERR! System Linux 4.12.10-unRAID
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-              gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_              modules/pcap2
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
/usr/lib
└── (empty)

npm ERR! Linux 4.12.10-unRAID
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "h              omebridge-platform-ring-video-doorbell"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! pcap2@3.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcap2@3.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pcap2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pcap2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pcap2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
npm ERR! code 1
root@MyServer:/#

**Comment by mrose17** [comment]
did you try `apt-get install libpcap-dev` ?

**Comment by CanonCan** [comment]
yes and it fails....here is my output

root@MyServer:/# apt-get install libpcap-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libpcap-dev
root@MyServer:/#

**Comment by CanonCan** [comment]
@mrose17 when you correct the compile can you post here so us users can try it again?

**Comment by mrose17** [comment]
sorry, i was unclear: in order for this package to work. you have to already have libpcap-dev on your system. that is a "system requirement".

**Comment by CanonCan** [comment]
and when your "apt-get install libpcap-dev" fails what are we to do?

**Comment by mrose17** [comment]
you could contact technical support for your device and ask how `libpcap-dev` should be installed. perhaps they have a different install mechanism than `apt-get`
