### ISSUE TITLE
Installation on RPi 2 fails

### ISSUE THREAD

**Issue by ktsi** [homespun/homebridge-platform-ring-video-doorbell#2]
Here is the error message:

compilation terminated.
pcap_binding.target.mk:93: recipe for target 'Release/obj.target/pcap_binding/src/pcap_binding.o' failed
make: *** [Release/obj.target/pcap_binding/src/pcap_binding.o] Error 1
make: Leaving directory '/usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap2/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.35-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap2
gyp ERR! node -v v6.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/usr/lib
└── (empty)

npm ERR! Linux 4.4.35-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge-platform-ring-video-doorbell" "--unsafe-perm"
npm ERR! node v6.9.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pcap2@3.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap2@3.0.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pcap2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pcap2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pcap2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
npm ERR! code 1

**Comment by kieranmjones** [comment]
I also encountered this problem, I believe I had several issues at once which makes pinpointing precisely what fixed it tricky but I believe the thing that did it was installing libpcap-dev package.

apt-get install libpcap-dev

I then installed this module with the following,

sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell

It may well be that actually it was only one of these steps that fixed it, or none of them, I was getting so annoyed by this point I was not being especially scientific! It is however working now on my Pi

**Comment by ktsi** [comment]
It seems that it works for me as well. Thanks a lot mate.

**Comment by kieranmjones** [comment]
Great! Glad I was able to help!

**Comment by ktsi** [comment]
Well i am not so sure. I will get back to you.

**Comment by mrose17** [comment]
@kieranmjones - thanks for the pointer. i'll update the README on the next push (probably this weekend)

**Comment by triestelaporte** [comment]
Anyone tried this on FreeBSD (FreeNAS Jail)?  Looks like libpcap-dev is not a package we can install, yet we receive the same error when attempting the npm install.

**Comment by mrose17** [comment]
(-;
