### ISSUE TITLE
refres1 { Username......

### ISSUE THREAD

**Issue by hjhmedia** [homespun/homebridge-platform-ring-video-doorbell#20]
I keep on getttiig this error

[9/25/2017, 8:03:53 PM] [Doorbell] refresh1 { username: 'harrison@hjh-media.com' }

I have checke my username and passowwrd and i am still getting the same error

Heres my config File.

{
  "bridge": {
    "name": "HomeBridge 4.0",
    "username": "CC:22:3D:E3:CE:27",
    "port": 51826,
    "pin": "189-34-259"
  },
  "description": "This is our Homebridge configuration file",
  "accessories": [
    {
      "accessory": "WUNDERGROUND",
      "name": "Weather Underground",
      "device": "WURGrafton",
      "key": "4fd4452bc4f59dbe",
      "city": "Australia/Grafton"
    },
        {
      "accessory": "WUNDERGROUND",
      "name": "Weather Underground 1",
      "device": "WURGraftdon",
      "key": "4fd4452bc4f59dbe",
      "city": "Australia/Grafton"
    }
  ],
  "platforms": [
    {
      "platform": "BelkinWeMo",
      "name": "Pool Filter",
      "description": "Pool Filter",
      "BelkinWeMo_name": "Pool Filter"
    },    
    {
      "platform": "BelkinWeMo",
      "name": "Desk Lamp",
      "description": "Pool Filter",
      "BelkinWeMo_name": "Desk Lamp"
    },
    {
      "platform": "Arlo",
      "name": "Arlo",
      "email": "h@hjh-media.com",
      "password": "Not so fast"
    },
   {
       "platform": "LifxLan",
       "name": "LiFx"
   },
        {
      "platform": "HarmonyHub",
      "name": "Harmony Hub"
    },
    { "platform"  : "ring-video-doorbell"
, "name"      : "Doorbell"
, "username"  : "harrison@hjh-media.com"
, "password"  : "took this out just for the psot"
    }
  ]
}

**Comment by mrose17** [comment]
that's very odd indeed. try this: edit the file homebridge-platform-ring-video-doorbell/node_modules/doorbot/doorbot.js

look for this function:


    simpleRequest(url, method, callback) {
        this.authenticate(() => {
            this.fetch(method, url, {
                api_version: API_VERSION,
                auth_token: this.token
            }, null, (e, res, json) => {
                if (e && e.code === 401 && this.counter < this.retries) {
                    logger('auth failed, retrying');
                    this.counter += 1;
                    setTimeout(() => {
                        this.token = null;
                        this.authenticate((e) => {
                            /*istanbul ignore next*/
                            if (e) {
                                return callback(e);
                            }
                            this.simpleRequest(url, method, callback);
                        });
                    }, 500);
                    return;
                }
                this.counter = 0;
                callback(e, res, json);
            });
        });
    }

between these two lines:

            }, null, (e, res, json) => {
                if (e && e.code === 401 && this.counter < this.retries) {

add this line:

                if (e) console.log(JSON.stringify(e, null, 2))

then restart homebridge. if you didn't introduce any errors into the file, before you see this line:

    [9/25/2017, 8:03:53 PM] [Doorbell] refresh1 { username: 'harrison@hjh-media.com' }

you should see some more debug output. please add that to this issue.

good luck!

**Comment by hjhmedia** [comment]
@Mrose17 Sorry I'm a bit dumb with my mac. How do i get to that file ?

Thanks

**Comment by mrose17** [comment]
if you installed with `npm -g ...`, there is probably a directory somewhere under `/usr/local` called `homebridge-platform-ring-video-doorbell`, so you can try

    find /usr/local -name homebridge-platform-ring-video-doorbell -print

and see if that finds it for you.

good luck!

**Comment by hjhmedia** [comment]
Working Fine now. Thanks so much for the Help ! I will add any debug output when i see it. Thanks

**Comment by hjhmedia** [comment]
@mrose17 

i am now getting this.
[9/28/2017, 8:15:14 PM] [Doorbell] refresh1 { username: 'harrison@hjh-media.com',
  code: 'ENETDOWN',
  errno: 'ENETDOWN',
  syscall: 'read' }

**Comment by mrose17** [comment]
that's great progress!

usually `ENETDOWN` means just what it says; however, i am told by "the google" that occasionally it means that the server can't be reached. since this is occurring on a `read`, it sounds like a connection is being established, but a network error occurs when trying to read data from the connection.

i think your best bet is to go to https://github.com/davglass/doorbot/issues/new and open an issue with the doorbot repository. reference this issue -- https://github.com/homespun/homebridge-platform-ring-video-doorbell/issues/20 -- so @davglass can have context.

good luck!

**Comment by sdorilas** [comment]
I'm having the same exact issue and for the life of me, I cannot locate any directories for me to edit the file listed above.

**Comment by phis5533** [comment]
Hello, I'm having the same issue and my return code is :

{
  "code": 401
}

Any ideas ??

Thanks
