### ISSUE TITLE
Remove door bell services from cameras

### ISSUE THREAD

**Issue by Cardo1** [homespun/homebridge-platform-ring-video-doorbell#22]
In the current version, the plugin exposes a "Door Bell" service even if the device is a camera only device.  This doesn't show up in the native Home app, however does show up in third party apps.  Would it be possible to remove the Door Bell service for those devices that don't have door bells?

Cheers.

**Comment by mrose17** [comment]
good catch! i hope to publish 0.6.0 later today with that fix... thanks!

**Comment by mrose17** [comment]
0.6.0 is published
