### ISSUE TITLE
Doesn't Support Ring Doorbell Pro

### ISSUE THREAD

**Issue by washcroft** [homespun/homebridge-platform-ring-video-doorbell#24]
Hello,
The plugin doesn't support Ring Doorbell Pro, instead it appears in HomeKit as a stickup cam. This is because the device kind is no longer "doorbell", but is "lpd_v2" for the Pro (line 174 expects "doorbell").

Perhaps the Doorbell v2 and the Doorbell Elite have different kinds too?

**Comment by mrose17** [comment]
thanks for the report. i just published 0.6.5 ... please see if that works!

**Comment by washcroft** [comment]
Yes, fixed. Thanks.

**Comment by mrose17** [comment]
great, thanks for the report!

**Comment by mrose17** [comment]
well, it's a warning. can you tell me

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!

**Comment by mkormendy** [comment]
Thanks for all of your work on this project in the past Marshall!!
