### ISSUE TITLE
Camera Integration

### ISSUE THREAD

**Issue by ayanm00** [homespun/homebridge-platform-ring-video-doorbell#25]
Hi,
Do you see camera integration being added in the near future? By the way, Best Buy is currently offering the first generation Ring for $100, if anyone else wants to pick one up. 

Thanks!

**Comment by theo-69** [comment]
that would be great!

**Comment by lawrence-jeff** [comment]
One more vote for camera support - would love to leverage with a pi (and an attached camera module)

**Comment by bjornand1** [comment]
Count me in for this! However, I am struggling to understand what the reference to homebridge-camera-ffmpeg means; does it mean installing this plugin and placing it in the same room as the Ring doorbell, I will be able to get the video feed from the doorbell?

**Comment by gilbert76** [comment]
can me someone explane who i can integrate the camera. I installed the homebridge-camera-ffmpeg but i don't know who i can configure the camera, so after them i can see it in the Home.app.

**Comment by mkormendy** [comment]
*/ cross posted from reddit */

According to the https://github.com/tchellomello/python-ring-doorbell/issues/23 there is a handshake that happens between the Ring Doorbell and the Ring API on the Ring Servers. The Ring Clients that play the streamed video initiate a request to the Ring API first. Meanwhile the Ring Doorbell is continuously polling the Ring Servers and asking the API if someone has requested a live video. If so, the the Ring API provides the the details of the initiated request to the Ring Doorbell which then opens up a stream address, at which it becomes available to the Ring Client which is redirected by the confirmation from the API to the Ring Doorbell stream.

Meanwhile there's also some recording that goes on, and the video is also uploaded to the Ring Servers as a recorded session .. the max length of which I am not sure.

That all being said, you'd have to recreate the handshake between the Ring Servers and the Ring Doorbell as well as the Ring Client to get the doorbell device to open up a live stream for the video.

I believe that @barkerja was only postulating and had no real proof that any of what he said would actually happen.

Good luck!

**Comment by theo-69** [comment]
any updates on integration?

**Comment by mkormendy** [comment]
@theo-69 integration will likely not happen.

**Comment by theo-69** [comment]
any update on this?

**Comment by theo-69** [comment]
its now working with echo show, any update on homebridge?

**Comment by mkormendy** [comment]
Well, since Ring is now owned by Amazon, it's no surprise that they've got unfettered access to the Ring API and authentication pipeline to get streaming video on any of their devices. @theo-69 don't hold your breath.

**Comment by krazyflipj** [comment]
Will you get video screenshots if you setup with Home Assistant as described above and link to homebridge?

**Comment by ifeign** [comment]
Try it and let us know. I don't think any of us here use Home Assistant,
this being a Homebridge plugin we're discussing.

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
