### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by tuomaslaa** [homespun/homebridge-platform-ring-video-doorbell#26]
Can't run module. Installed it with:

sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell

Startup Log:

ov 20 19:11:08 homebridge homebridge[20627]: [2017-11-20 19:11:08] ====================
Nov 20 19:11:08 homebridge homebridge[20627]: [2017-11-20 19:11:08] ERROR LOADING PLUGIN homebridge-platform-ring-video-doorbell:
Nov 20 19:11:08 homebridge homebridge[20627]: [2017-11-20 19:11:08] Error: Cannot find module './build/Release/pcap_binding'
Nov 20 19:11:08 homebridge homebridge[20627]:     at Function.Module._resolveFilename (module.js:536:15)
Nov 20 19:11:08 homebridge homebridge[20627]:     at Function.Module._load (module.js:466:25)
Nov 20 19:11:08 homebridge homebridge[20627]:     at Module.require (module.js:579:17)
Nov 20 19:11:08 homebridge homebridge[20627]:     at require (internal/module.js:11:18)
Nov 20 19:11:08 homebridge homebridge[20627]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap2/index.js:6:22)
Nov 20 19:11:08 homebridge homebridge[20627]:     at Module._compile (module.js:635:30)
Nov 20 19:11:08 homebridge homebridge[20627]:     at Object.Module._extensions..js (module.js:646:10)
Nov 20 19:11:08 homebridge homebridge[20627]:     at Module.load (module.js:554:32)
Nov 20 19:11:08 homebridge homebridge[20627]:     at tryModuleLoad (module.js:497:12)
Nov 20 19:11:08 homebridge homebridge[20627]:     at Function.Module._load (module.js:489:3)
Nov 20 19:11:08 homebridge homebridge[20627]: [2017-11-20 19:11:08] ====================

**Comment by timhng** [comment]
I had exactly the same issue.

**Comment by mrose17** [comment]
@timhg - if there's a fix, let me know. i can't reproduce it.

**Comment by mrwaltern** [comment]
Any updates on this issue? I'm having the same problem now.

**Comment by leinieboy** [comment]
I got mine to work by:

cd /usr/local/lib/node_modules/
git clone git://github.com/mranney/node_pcap.git
mv node_pcap pcap2
cd pcap2
npm install
cd ..
cp -R pcap2 homebridge-platform-ring-video-doorbell/node_modules/

Then ran homebridge and it loaded up..  sorry for all the terminal commands I get confused when people say just replace the pcap2 with one installed from source, so I wanted to make sure I was clear.

**Comment by mrose17** [comment]
sorry for the delay in replying. please try the latest version that uses the latest version of pcap!
