### ISSUE TITLE
Seeing a refresh1 error running the plugin

### ISSUE THREAD

**Issue by joewilliamsca** [homespun/homebridge-platform-ring-video-doorbell#28]
HI all

Just giving the plugin a whirl on my Raspberry PI.

it looks like the devices are being registered in homekit from Ring.com,  but it appears the api call is failing,  and causing a refresh/error. 

[2018-1-8 03:40:19] [Doorbell] refresh1 { username: 'xxx@icloud.com' }

Looks like the return value of err is empty.. 

Any thoughts on how to further debug the issue?  Im thinking something is failing in the RingAPI package...

I have a stickup camera and a doorbell,  and I just want to get the motion sensors to work with homebridge.

Any thoughts?
Cheers,
-Joe

**Comment by joewilliamsca** [comment]
[ring-homebridge.txt](https://github.com/homespun/homebridge-platform-ring-video-doorbell/files/1628536/ring-homebridge.txt)

Hey All,

So after further debugging,  I found out that I was sending too many requests to api.ring.com,  and the site began to block my calls.

I ended up turning on debug in homebridge,  and going through the debug logs,  and what I did see is that there is some event that is causing the plugin to reconnect to the api.ring.com,  and request a new authentication token.  This happened for 7 times,  and then the site decided to ban my IP for 5 min to prevent further spiking 

The authentication parameters do work as I see the details from my account appear in the log (which I have attached and scrubbed of my personal information.  Looks like something  interesting is happening.  I have also dumped the results of npm list -g too.

Any thoughts?  
[npmlist.txt](https://github.com/homespun/homebridge-platform-ring-video-doorbell/files/1628544/npmlist.txt)

**Comment by tbelcher** [comment]
Joe - I'm seeing a similar issue here.  Ring is using Cloudflare to block my IP, but I'm not sure why.  Logging shows the following:
Jan 27 18:39:09 raspberrypi homebridge[6712]: Sun, 28 Jan 2018 02:39:09 GMT doorbot authenticating..
Jan 27 18:39:09 raspberrypi homebridge[6712]: Sun, 28 Jan 2018 02:39:09 GMT doorbot fetch: 0 POST /session
Jan 27 18:39:09 raspberrypi homebridge[6712]: Sun, 28 Jan 2018 02:39:09 GMT doorbot fetch-data Url {
Jan 27 18:39:09 raspberrypi homebridge[6712]: protocol: 'https:',
Jan 27 18:39:09 raspberrypi homebridge[6712]: slashes: true,
Jan 27 18:39:09 raspberrypi homebridge[6712]: auth: null,
Jan 27 18:39:09 raspberrypi homebridge[6712]: host: 'api.ring.com',
Jan 27 18:39:09 raspberrypi homebridge[6712]: port: null,
Jan 27 18:39:09 raspberrypi homebridge[6712]: hostname: 'api.ring.com',
Jan 27 18:39:09 raspberrypi homebridge[6712]: hash: null,
Jan 27 18:39:09 raspberrypi homebridge[6712]: search: '',
Jan 27 18:39:09 raspberrypi homebridge[6712]: query: {},
Jan 27 18:39:09 raspberrypi homebridge[6712]: pathname: '/clients_api/session',
Jan 27 18:39:09 raspberrypi homebridge[6712]: path: '/clients_api/session',
Jan 27 18:39:09 raspberrypi homebridge[6712]: href: 'https://api.ring.com/clients_api/session' }
Jan 27 18:39:09 raspberrypi homebridge[6712]: Sun, 28 Jan 2018 02:39:09 GMT doorbot fetch-headers { Authorization: 'Basic __redacted_'_,
Jan 27 18:39:09 raspberrypi homebridge[6712]: 'content-type': 'application/x-www-form-urlencoded',
Jan 27 18:39:09 raspberrypi homebridge[6712]: 'content-length': 141,
Jan 27 18:39:09 raspberrypi homebridge[6712]: 'user-agent': '@nodejs-doorbot' }
Jan 27 18:39:09 raspberrypi homebridge[6712]: Sun, 28 Jan 2018 02:39:09 GMT doorbot fetch-post username=redacted&password=redacted&device%5Bos%5D=ios&device%5Bhardware_id%5D=ad7adf22188b916296811416ec06fc49&api_version=9
Jan 27 18:39:09 raspberrypi homebridge[6712]: Sun, 28 Jan 2018 02:39:09 GMT doorbot fetch-raw-data <!DOCTYPE html>
Jan 27 18:39:09 raspberrypi homebridge[6712]: 
Jan 27 18:39:09 raspberrypi homebridge[6712]: 
Jan 27 18:39:09 raspberrypi homebridge[6712]: 
Jan 27 18:39:09 raspberrypi homebridge[6712]:  <html class="no-js" lang="en-US"> 
Jan 27 18:39:09 raspberrypi homebridge[6712]: <head>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <title>Access denied | api.ring.com used Cloudflare to restrict access</title>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <meta charset="UTF-8" />
Jan 27 18:39:09 raspberrypi homebridge[6712]: <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
Jan 27 18:39:09 raspberrypi homebridge[6712]: <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
Jan 27 18:39:09 raspberrypi homebridge[6712]: <meta name="robots" content="noindex, nofollow" />
Jan 27 18:39:09 raspberrypi homebridge[6712]: <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
Jan 27 18:39:09 raspberrypi homebridge[6712]: <link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
Jan 27 18:39:09 raspberrypi homebridge[6712]: 
Jan 27 18:39:09 raspberrypi homebridge[6712]: <style type="text/css">body{margin:0;padding:0}</style>
Jan 27 18:39:09 raspberrypi homebridge[6712]: 
Jan 27 18:39:09 raspberrypi homebridge[6712]: <script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>
Jan 27 18:39:09 raspberrypi homebridge[6712]: </head>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <body>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <div id="cf-wrapper">
Jan 27 18:39:09 raspberrypi homebridge[6712]: <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <div id="cf-error-details" class="cf-error-details-wrapper">
Jan 27 18:39:09 raspberrypi homebridge[6712]: <div class="cf-wrapper cf-header cf-error-overview">
Jan 27 18:39:09 raspberrypi homebridge[6712]: <h1>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <span class="cf-error-type" data-translate="error">Error</span>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <span class="cf-error-code">1015</span>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <small class="heading-ray-id">Ray ID: 3e409463c8897c28 &bull; 2018-01-28 02:39:09 UTC</small>
Jan 27 18:39:09 raspberrypi homebridge[6712]: </h1>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <h2 class="cf-subheadline" data-translate="error_desc">You are being rate limited</h2>
Jan 27 18:39:09 raspberrypi homebridge[6712]: </div>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <section></section>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <div class="cf-section cf-wrapper">
Jan 27 18:39:09 raspberrypi homebridge[6712]: <div class="cf-columns two">
Jan 27 18:39:09 raspberrypi homebridge[6712]: <div class="cf-column">
Jan 27 18:39:09 raspberrypi homebridge[6712]: <h2 data-translate="what_happened">What happened?</h2>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <p>The owner of this website (api.ring.com) has banned you temporarily from accessing this website.</p>
Jan 27 18:39:09 raspberrypi homebridge[6712]: </div>
Jan 27 18:39:09 raspberrypi homebridge[6712]: </div>
Jan 27 18:39:09 raspberrypi homebridge[6712]: </div>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <div class="cf-error-footer cf-wrapper">
Jan 27 18:39:09 raspberrypi homebridge[6712]: <p>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <span class="cf-footer-item">Cloudflare Ray ID: <strong>3e409463c8897c28</strong></span>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <span class="cf-footer-separator">&bull;</span>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 172.91.241.123</span>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <span class="cf-footer-separator">&bull;</span>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">Cloudflare</a></span>
Jan 27 18:39:09 raspberrypi homebridge[6712]: </p>
Jan 27 18:39:09 raspberrypi homebridge[6712]: </div>
Jan 27 18:39:09 raspberrypi homebridge[6712]: </div>
Jan 27 18:39:09 raspberrypi homebridge[6712]: </div>
Jan 27 18:39:09 raspberrypi homebridge[6712]: <script type="text/javascript">
Jan 27 18:39:09 raspberrypi homebridge[6712]: window._cf_translation = {};
Jan 27 18:39:09 raspberrypi homebridge[6712]: </script>
Jan 27 18:39:09 raspberrypi homebridge[6712]: </body>
Jan 27 18:39:09 raspberrypi homebridge[6712]: </html>

**Comment by joewilliamsca** [comment]
thanks @tbelcher 

Glad im not the only one running into the problem.  If I get some time tomorrow,  I might go and reproduce the problem with the RingAPI that this plugin is using to see if i can find root cause.  If not tomorrow,  most likely I will see if I can make some headway in the next couple of weeks.

**Comment by phis5533** [comment]
Hi all,

It seems I've got a similar issue... 
Since I've got 401 error 
{
401
 }
[Doorbell] refresh1 { username: 'xxxxx@me.com' }

Have you got some kind of solution ?? 
Thx
BR

**Comment by Hucksleyy91** [comment]
hey has anyone fixed this im seeing this error

**Comment by mrose17** [comment]
sorry for the delay in replying. please try the latest version that uses the latest version of doorbot!

**Comment by mrose17** [comment]
@Hucksleyy91  - please submit a new issue, also if you run homebridge as

        DEBUG=ring-video-doorbell homebridge

what gets logged for the error?
