### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by obarber** [homespun/homebridge-platform-ring-video-doorbell#30]
When I go to install the plugin, it gives me the following error:

npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/homespun/hap-nodejs-community-types.git /Users/oli/.npm/_cacache/tmp/git-clone-e9e13ef3
npm ERR! /Users/oli/.npm/_cacache/tmp/git-clone-e9e13ef3/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oli/.npm/_logs/2018-02-10T12_03_31_844Z-debug.log

I have installed this plugin exactly the same as I have with my others, using:

sudo npm install -g --unsafe-perm homebridge
sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell

Which is then when I get the above error

Does anyone know where I'm going wrong?

Thanks.

**Comment by kieranmjones** [comment]
I have encountered the exact same problem, I've yet to find a solution to the problem though unfortunately. If I find one I will let you know!

**Comment by bjornand1** [comment]
Hi, I have homebridge running on a Synology NAS using the oznu installation that allows installing plugins through the browser interface. When trying to install, I do get the error "node-gyp rebuild" and so on (see below). Is there any way to run the "% apt-get install libpcap-dev" and "% sudo npm install -g homebridge-platform-ring-video-doorbell" commands to install the ring plugin when running homebridge this way?

USER: root
DIR: /homebridge
CMD: npm install --unsafe-perm --save homebridge-platform-ring-video-doorbell@latest


> socketwatcher@0.3.0 install /homebridge/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory '/homebridge/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp: In static member function 'static void SocketWatcher::New(const Nan::FunctionCallbackInfo<v8::Value>&)':
../socket_watcher.cpp:104:49: warning: 'v8::Local<v8::Object> v8::Function::NewInstance() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     info.GetReturnValue().Set(cons->NewInstance());
                                                 ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/root/.node-gyp/8.9.4/include/node/v8.h:3836:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/homebridge/node_modules/socketwatcher/build'

> pcap2@3.0.4 install /homebridge/node_modules/pcap2
> node-gyp rebuild

make: Entering directory '/homebridge/node_modules/pcap2/build'
  CXX(target) Release/obj.target/pcap_binding/src/pcap_binding.o
../src/pcap_binding.cc:2:23: fatal error: pcap/pcap.h: No such file or directory
 #include <pcap/pcap.h>
                       ^
compilation terminated.
make: *** [pcap_binding.target.mk:96: Release/obj.target/pcap_binding/src/pcap_binding.o] Error 1
make: Leaving directory '/homebridge/node_modules/pcap2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.102
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /homebridge/node_modules/pcap2
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcap2@3.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcap2@3.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-23T05_48_59_074Z-debug.log

Command failed. Please review log for details

**Comment by iogitio** [comment]
I have a similar issue with running on Synology NAS, I think it has to do with libpcap... is there a way we can install this or have it integrated into the docker container?

**Comment by joshbish** [comment]
I have the same issue as the OP

**Comment by bjornand1** [comment]
Hope someone who knows the way around this stuff could help! We can run terminal commands in Docker, but it seems the paths or something else is different that means the posted solution doesn’t work.

**Comment by Scirocco3** [comment]
Same her on syno NAS. trouble to instal libpcap and apt-get won't work.

**Comment by ybouckaert** [comment]
Hello,

I was having trouble installing this plugin too. What did the trick was at the command prompt typing "sudo su", and then "npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell".

Regards,
Yann

**Comment by Scirocco3** [comment]
Wont work on the Docker Image on the syno NAS. There is no sudo command...

**Comment by bjornand1** [comment]
That is my problem, I just can't figure out how to run the installation and avoid the "node-gyp rebuild" error.

**Comment by dewilded** [comment]
Getting this error when following the install instructions.

pi@raspberrypi:~/.homebridge $ sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-71fcaf44
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-71fcaf44': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-16T06_11_16_528Z-debug.log


I get that error even when running this sequence:

pi@raspberrypi:~/.homebridge $ sudo su
root@raspberrypi:/home/pi/.homebridge# npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell

**Comment by mrwaltern** [comment]
Exact same issue as dewilded, running on a raspberry pi 3.

**Comment by rrrkren** [comment]
to all those using the oznu docker image, since the linux distribution used is alpine, you gotta run this to install the libpcap image:
apk add libpcap-dev

**Comment by iogitio** [comment]
@rrrkren is it possible to run that command inside Synology Docker?

**Comment by rrrkren** [comment]
@iogitio Yes. Go to terminal view of the container and execute the command there

**Comment by edwinvanwijk** [comment]
I am having the same problem as @dewilded when trying to install the plugin:

I run the command:  sudo npm install -g homebridge-platform-ring-video-doorbell

npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-9759b99c
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-9759b99c': Toegang geweigerd
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-02T15_12_00_586Z-debug.log

Any thoughts on how to fix this?

**Comment by iogitio** [comment]
bump :)

**Comment by gilbert76** [comment]
i have the same problem

**Comment by gilbert76** [comment]
i solve the problem wit this commands
sudo npm i -g npm
after them  
npm insall -g  homebridge-platform-ring-video-doorbell
