### ISSUE TITLE
Can't get Bell in Home App

### ISSUE THREAD

**Issue by phis5533** [homespun/homebridge-platform-ring-video-doorbell#32]
Hello everybody, especially @mrose17 

I can't succeed make Bell Ring appears in the Home app !
I just have Ring Motion Sensor but no Bell....
I don't know if it's because of that :

{
  "code": 401
}
[09/03/2018 à 19:07:35] [Doorbell] refresh1 { username: 'xxx@me.com' }

If someone has an answer :-)....

Thx 
BR

Edit : I've just seen a post from last year which explain Door Bell button doesn't appear in Home App but in Hesperus... Does have it change today ??

**Comment by Hucksleyy91** [comment]
No it is not in the home app but you can use the 3rd party app to create a scene with that button in it. It will then show in the home app

**Comment by phis5533** [comment]
Thx for the trick !
