### ISSUE TITLE
Fails to install on Windows 10 Homebridge

### ISSUE THREAD

**Issue by TharuMCD** [homespun/homebridge-platform-ring-video-doorbell#34]
Dear community,

I have installed the latest version of Homebrige (0.4.38) on a 64 bit Windows 10 machine using the instructions at https://github.com/nfarina/homebridge/wiki/Install-HomeBridge-on-Windows-10-(new)

I then tried to install this platform using the npm install-g command.  

Failed to install.  Tried to solve by manually installing Git-2.17.0-64-bit, which took the process of installation a little further before again running into an error regarding pcap.  Tried installing WinPcap_4_1_3 to no avail.

Just wondered if anyone else might have succeeded?

With kind regards,
Michael.
[2018-04-21T22_26_38_594Z-debug.log](https://github.com/homespun/homebridge-platform-ring-video-doorbell/files/1935048/2018-04-21T22_26_38_594Z-debug.log)

**Comment by iRayanKhan** [comment]
Alot of plugins I see only work on macOS/Linux idk why. Try getting a raspberry Pi. I have a Pi 3 model B they're dirt cheap $25/each Pi and the one I got had a free 16gb micro sd card. Check ebay. Also idk if doorbells still work.

**Comment by mrose17** [comment]
sorry for the delay in replying. please try the latest version that uses the latest version of pcap that should work on windows
