### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by rtjdamen** [homespun/homebridge-platform-ring-video-doorbell#36]
When i try to install the plugin i get the below error. anyone an idea how to resolve? or can i do a manual install. i am running Chroot on Synology. Other plugin installations are going without issues

root@NLRDMHUB01:~/local/lib/node_modules# npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
npm ERR!
npm ERR! fatal: Cannot change to '/root/local/..': Permission denied
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-07T06_48_22_866Z-debug.log
root@NLRDMHUB01:~/local/lib/node_modules#

Thanks!

**Comment by gilbert76** [comment]
I have the same problem

**Comment by gilbert76** [comment]
i solve the problem wit this commands
sudo npm i -g npm
after them  
npm insall -g  homebridge-platform-ring-video-doorbell
