### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ketansweta** [homespun/homebridge-platform-ring-video-doorbell#37]
C:\Users\Ketan.Parekh\Downloads\homebridge-platform-ring-video-doorbell-master\homebridge-platform-ring-video-doorbell-master>npm install -g homebridge
C:\Users\Ketan.Parekh\AppData\Roaming\npm\homebridge -> C:\Users\Ketan.Parekh\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge

> curve25519-n@1.4.0 install C:\Users\Ketan.Parekh\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n
> node-gyp rebuild

C:\Users\Ketan.Parekh\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Users\Ketan.Parekh\Python\Python35-32\python.EXE" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:195:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:891:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:342:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:497:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Ketan.Parekh\AppData\Roaming\npm\node_modules\homebridge\node_modules\curve25519-n
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
C:\Users\Ketan.Parekh\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "homebridge"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! curve25519-n@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the curve25519-n@1.4.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the curve25519-n package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs curve25519-n
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls curve25519-n
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Ketan.Parekh\Downloads\homebridge-platform-ring-video-doorbell-master\homebridge-platform-ring-video-doorbell-master\npm-debug.log
npm ERR! code 1
[npm-debug.log](https://github.com/homespun/homebridge-platform-ring-video-doorbell/files/2086933/npm-debug.log)

**Comment by ketansweta** [comment]
Upgraded npm to make sure. Still same error. PLease help.
[npm-debug.log](https://github.com/homespun/homebridge-platform-ring-video-doorbell/files/2086947/npm-debug.log)

**Comment by ddoria921** [comment]
I'm running into the same issue myself

**Comment by ddoria921** [comment]
@ketansweta I was able to get past that error by following the solution listed here https://github.com/nodejs/node-gyp/issues/809

> Delete your `$HOME/.node-gyp` directory and try again.
