### ISSUE TITLE
Install working but not loading Doorbell

### ISSUE THREAD

**Issue by BAngel87** [homespun/homebridge-platform-ring-video-doorbell#38]
I have installed the plugin and edited my config:

	{ "platform"  : "ring-video-doorbell",
	"name"      : "Doorbell",
 "username"  : "timx@xal.me",
 "password"  : "xxxx",
"options"   : { "retries": 15, "ttl": 5, "verboseP" : false }
},

when I then restart my Homebridge the ring-video-doorbell platform is loaded: It says: didFinishLaunching but sadly no new devices are showing and also I can't see any connection tries in the Log

I also tried verbose mode but same output.

Hope you can help me,...

Greetings

**Comment by zmclearan** [comment]
This plugin was working for me up until a few weeks ago. Now I’m getting an error message in the log saying theres something wrong with my account info. I have a feeling that Ring may have changed something on their end which interferes with this plugin. I think this might be why you aren’t seeing your doorbell in Home.

If anyone else out there knows something more about this I’d love to know.

**Comment by BAngel87** [comment]
Update: 
Solved it by basically including the pull request (ef79aab3c55b54283f7d9c8da73873f6df26cd6a).

The pull request is from the fork of @davglass and included in the doorbot5 branch.

And in addition I changed the ttl to 45 so it seams like I'm also getting motion events correct.

**Comment by Hucksleyy91** [comment]
i just installed this plugin with the homebridge app and added to the config is there something else i have to do i see i have to install 5.0 instead as homebridge wont load at all for me anymore

**Comment by BAngel87** [comment]
I now tried everything but the Plugin is not working usefully, sadly it seams like Ring is blocking the connection to the server when ttl is smaller than 45 Seconds. But 45 Seconds is to long to use the Doorbell in Homekit,.... Come On Ring when is the native Homekit Integration coming? Are you all only at the sea in California?

**Comment by Hucksleyy91** [comment]
my ttl is set to 5 and I haven’t been blocked yet I was getting refresh1 errors but then I done a npm -g install in the ring module folder and it worked straight away :) I don’t get the button in the home app but it is in the Eve app

**Comment by mrose17** [comment]
sorry for the delay in replying. please try the latest version that uses the latest version of doorbot!
