### ISSUE TITLE
should I update and how?

### ISSUE THREAD

**Issue by Hucksleyy91** [homespun/homebridge-platform-ring-video-doorbell#40]
Did just notice 3 files changed how do I update them ?
Copy paste then npm -g update in directory ? My bell is working fine

**Comment by phis5533** [comment]
Hello again Hucksleyy91,

When you say your Bell works, you mean the ring or the motion sensor or the camera or everything ?
I have the motion sensor ok, the button is in Eve, but doesn’t seem to work... can you post some details please ?
Thx 
Phil

**Comment by Hucksleyy91** [comment]
Are you trying to make a rule ? Use the doorbell button DOUBLE PRESS as the trigger, then set maybe a scene of some light as 98%brighness blue means button is pressed then turns off after 1minute so in the home app you can see the scene activate when button is pressed :)

**Comment by phis5533** [comment]
I've tried with only ONE PRESS as the trigger...
I'll try tonight with the DOUBLE PRESS :-) 

Thanks a lot

**Comment by Hucksleyy91** [comment]
No problem that should do the trick it did for me :) also set the ttl to 5 for the best response :) any lower and ring give you a 5 min ban

**Comment by phis5533** [comment]
Hi @Hucksleyy91 !

I've tried a rule with might switch on light, with One press, double press or long press and the scene doesn't apply..... :( 
I've made the rule trough Eve app...
I can't understand....
If you have a trick.....
Thx
