### ISSUE TITLE
Unable to get motion

### ISSUE THREAD

**Issue by gilbert76** [homespun/homebridge-platform-ring-video-doorbell#42]
Hello,
Unfortunately, I get no message when something moves.

**Comment by mkormendy** [comment]
@mrose17 I am having the same issues. How can we debug?

**Comment by jocamero** [comment]
Same.  Anyone get this working?

**Comment by mdrzml** [comment]
digging through @davglass original API, i found this thread:

https://github.com/davglass/doorbot/issues/18

This plugin is still using API version 5.0.0. The fix is applied in 5.0.2. Maybe @mrose17 can up the version. That should fix this issue then.

**Comment by mdrzml** [comment]
Good news! I have tried updating the doorbot API version to at least 5.0.2 and it fixes the motion detection issues. 👍

**Comment by mrose17** [comment]
the current version of the plugin now uses doorbbot@5.2.0 ... thanks for the pointer!

**Comment by kharder69** [comment]
Am I missing something?  I have the motion sensor but it never detects motion.

**Comment by mrose17** [comment]
oops! i forgot to mention one thing, please look at the last image in https://github.com/homespun/homebridge-platform-ring-video-doorbell#motion-detector-notifications

**Comment by mkormendy** [comment]
> oops! i forgot to mention one thing, please look at the last image in https://github.com/homespun/homebridge-platform-ring-video-doorbell#motion-detector-notifications

**PARTICULARLY: "For your doorbell to generate motion notifications, you must use the Ring App to enable "Motion Alerts"**
