### ISSUE TITLE
Constant notifications of a doorbell ring

### ISSUE THREAD

**Issue by tbelcher** [homespun/homebridge-platform-ring-video-doorbell#43]
I have version 0.7.0 of the plugin installed and I'm getting notifications of a doorbell ring every minute (literally).  Anyone else having the same issue?  The syslog looks like I'm successfully connecting to api.ring.com and its reporting back my proper info.  Any ideas?

Thanks

Tim

**Comment by Djelibeybi** [comment]
I just came to report exactly the same thing.

**Comment by Hucksleyy91** [comment]
Use the double press method from the doorbell to activate somthing that’s acts as the doorbell in HomeKit, I noticed if I used the single press method it was being triggered every half minute or minute or so... 

Otherwise if there is issues I could upload a sd card file that’s ready to go with ring HAP homebridge everything...,

**Comment by mrose17** [comment]
sorry for the delay in replying. myself (and others!) are in the process of upgrading the plugin.  i hope to get to this issue this upcoming weekend.  for now: @Hucksleyy91 - what is the double press method?

**Comment by mj0500** [comment]
I'm seeing the same issue as well, running v0.7.9

**Comment by mj0500** [comment]
Just tested with v0.7.10 and it seems to be working well now. Thanks!

**Comment by mrose17** [comment]
i believe this is now fixed in version 0.8.1, i.e.,

        npm update -g homebridge-platform-ring-video-doorbell

and then restart homebridge

**Comment by kharder69** [comment]
This issue is still there.

**Comment by Hucksleyy91** [comment]
https://youtu.be/0UjJnVE0bZQ

So the ring send a SINGLE PRESS notification that you can only find in the EVE app or other 3rd party apps but if you use this DOUBLE PRESS METHOD I have found to make this plugin somewhat work

**Comment by kharder69** [comment]
@mrose17 I have currently uninstalled the plugin.  So if I install it first do I still need to do the update?  I am guessing not as it will install the latest version.

**Comment by mrose17** [comment]
either `install` or `update` will work!

just let me know what it says afterwards (since sometimes `npm` isn't current!)

thanks!

**Comment by kharder69** [comment]
Here is the results of the install.  Do you now want me to run the DEBUG= command?

**Comment by kharder69** [comment]
CXX(target) Release/obj.target/socketwatcher/socket_watcher.o                                                                                    
../socket_watcher.cpp: In static member function 'static void SocketWatcher::Callback(uv_poll_t*, int, int)':                                      
../socket_watcher.cpp:77:60: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Va
lue>*)' is deprecated (declared at ../../nan/nan.h:958) [-Wdeprecated-declarations]                                                                
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);                                                                                     
                                                            ^                                                                                      
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node                                                                                      
  COPY Release/socketwatcher.node                                                                                                                  
make: Leaving directory '/usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/socketwatcher/build'                           
                                                                                                                                                   
> pcap@2.0.0 install /usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap                                               
> node-gyp rebuild                                                                                                                                 
                                                                                                                                                   
make: Entering directory '/usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap/build'                                   
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o                                                                                       
  CXX(target) Release/obj.target/pcap_binding/pcap_session.o                                                                                       
../pcap_session.cc: In static member function 'static void PcapSession::PacketReady(u_char*, const pcap_pkthdr*, const u_char*)':                  
../pcap_session.cc:85:102: warning: 'v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Valu
e>*)' is deprecated (declared at ../../nan/nan.h:958) [-Wdeprecated-declarations]                                                                  
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), Nan::New(session->packet_ready_cb), 0, NULL);                                           
                                                                                                      ^                                            
  SOLINK_MODULE(target) Release/obj.target/pcap_binding.node                                                                                       
  COPY Release/pcap_binding.node                                                                                                                   
make: Leaving directory '/usr/lib/node_modules/homebridge-platform-ring-video-doorbell/node_modules/pcap/build'                                    
+ homebridge-platform-ring-video-doorbell@0.8.4                                                                                                    
added 39 packages from 64 contributors in 30.333s                                                                                                  
                                                                                                                                                   
                                                                                                                                                   
   ╭─────────────────────────────────────╮                                                                                                         
   │                                     │                                                                                                         
   │   Update available 5.8.0 → 6.4.0    │                                                                                                         
   │     Run npm i -g npm to update      │                                                                                                         
   │                                     │                                                                                                         
   ╰─────────────────────────────────────╯

**Comment by mrose17** [comment]
hmmm... i didn't see the results!  could you resend? also, please include the output. i will be out for the next 4 hours, so no rush!

**Comment by Vangel87** [comment]
I hope you will be able to solve this problem which I’m having as well. When I get back home later today I’ll do the same test and send you my log.

Best regards,
Remigiusz Szczerbak

**Comment by kharder69** [comment]
Any updates on this issue?

**Comment by mrose17** [comment]
here is what i understand. anyone here please feel free to clarify/correct my understanding.

1. the ring doorbell settings controls what circumstances indicates a motion event. on my doorbell, for example, i don't have motion detection turned on, and get only rings.

2. the code in the plugin, as of 0.8.1, suppresses contemporaneous identical events, i.e., if a ding is reported more than once, only the first ding is acted upon; further, if two dings are back-to-back, only state changes are reported. here is an example of how it works now:
          ring-video-doorbell new dings [] +5s
          ring-video-doorbell before    [] +0ms
        !!! update Front Doorbell: {
          "battery_level": 0,
          "battery_low": 0,
          "reachability": true,
          "motion_detected": false,
          "ringing": false
        }
          ring-video-doorbell after     [] +0ms
          ring-video-doorbell new dings [ { id: 6595138908285679000,
        ...
            state: 'ringing',
            doorbot_description: 'Front Doorbell',
            kind: 'ding',
        ... } ] +5s
          ring-video-doorbell before    [] +1ms
        !!! update Front Doorbell: {
          "battery_level": 0,
          "battery_low": 0,
          "reachability": true,
          "motion_detected": false,
          "ringing": true
        }
          ring-video-doorbell after     [ '6595138908285678871' ] +0ms
          ring-video-doorbell new dings [] +9s
          ring-video-doorbell before    [ '6595138908285678871' ] +0ms
        !!! update Front Doorbell: {
          "battery_level": 0,
          "battery_low": 0,
          "reachability": true,
          "motion_detected": false,
          "ringing": false
        }
          ring-video-doorbell after     [] +0ms
if  someone presses the doorbell again, and there is a a period between the two presses that results in no ringing being reported, then there will be two rings reported to homekit.

this leaves me at a loss to understand how multiple ring even

**Comment by kharder69** [comment]
Should the doorbell show up as an accessory?

I take it doing this will not resolve the incoming doorbell rang notification every minute in home app?

Ken

On Aug 29, 2018, at 10:23 AM, Marshall T. Rose <notifications@github.com<mailto:notifications@github.com>> wrote:


ps: since ringing is represented in homekit as a ProgrammableSwitchEvent which requires that you use it as a trigger in order to have something to happen, and motion is represented as a MotionDetected which shows up as a notification on iOS, i could add an option, so that ringing will trigger a MotionDetected as well. thoughts?

**Comment by mrose17** [comment]
It's fixed in `0.9.0` ... *hooray!*

 The doorbell does show up as an accessory. it shows up with two attributes, motion detection and programmable switch. They do different things.

attention @ Hucksleyy91 (and anyone else using the double-press trick): the default event generated by the plugin is now a single press. if you want to use `0.9.0` (or later) and keep the double-press, you want to add this line to the configuration for the plugin:

            , "ringing"   : { "event": "single", "motion": false }

the revised README file has the details.

**Comment by kharder69** [comment]
I will install and see but the last time I checked I had to motion sensors and no programmable switch.  If I have installed in past do I need to delete the Homebridge accessories/persist folders to get the right accessories to show up?

Ken

On Aug 29, 2018, at 7:38 PM, Marshall T. Rose <notifications@github.com<mailto:notifications@github.com>> wrote:


It's fixed in 0.9.0 ... hooray!

The doorbell does show up as an accessory. it shows up with two attributes, motion detection and programmable switch. They do different things.

attention @ Hucksleyy91 (and anyone else using the double-press trick): the default event generated by the plugin is now a single press. if you want to use 0.9.0 (or later) and keep the double-press, you want to add this line to the configuration for the plugin:

        , "ringing"   : { "event": "single", "motion": false }


the revised README file has the details.

**Comment by mrose17** [comment]
it's probably worthwhile to delete the accessory, just in case.

**Comment by kharder69** [comment]
Seems you can’t delete accessories in home app or are you referring to accessories folder?

Ken

On Aug 29, 2018, at 8:36 PM, Marshall T. Rose <notifications@github.com<mailto:notifications@github.com>> wrote:


it's probably worthwhile to delete the accessory, just in case.

**Comment by mrose17** [comment]
the accessories folder

**Comment by kharder69** [comment]
Deleted accessories directory and now I get only one accessory the motion sensor but nothing else.  Should I see the “no entry for lpd_v2” message?

This is what shows up in the homebridge.log file.

[8/30/2018, 12:01:10 PM] [Doorbell] doorbell { err: 'no entry for lpd_v2' }

!!! name=Front Door kind=doorbell model=lpd_v2 types=["ringing","motion_detected"] notices={"alerts":{"connection":"online"},"battery_life":3996}
[8/30/2018, 12:01:11 PM] [Doorbell] attachAccessory { uuid: 'b18b7d10-ef30-4b9c-a208-4a5960702e1c',
  name: 'Front Door',
  manufacturer: 'Bot Home Automation, Inc.',
  model: 'lpd_v2',
  serialNumber: '6353340',
  firmwareRevision: 'Up to Date' }
[8/30/2018, 12:01:11 PM] [Doorbell] addAccessory { uuid: 'b18b7d10-ef30-4b9c-a208-4a5960702e1c',
  name: 'Front Door',
  manufacturer: 'Bot Home Automation, Inc.',
  model: 'lpd_v2',
  serialNumber: '6353340’ }

Thanks,

Ken
On Aug 29, 2018, at 8:42 PM, Marshall T. Rose <notifications@github.com<mailto:notifications@github.com>> wrote:


the accessories folder

**Comment by mdrzml** [comment]
i think the programmable switch can only be seen in Elgato’s Eve app. the doorbell will not appear in Apple’s default Home app. only the motion sensor will appear in both Eve and Home apps. this is meant to be the way currently right @mrose17?

**Comment by mrose17** [comment]
https://github.com/homespun/homebridge-platform-ring-video-doorbell/blob/master/01.png shows what i see in elgato eve and there are two characteristics there... as to why you're not seeing both, i don't know.

**Comment by kharder69** [comment]
Ok I see it when I go into the motion sensor in eve.

Thanks,

Ken

On Aug 30, 2018, at 8:43 AM, Marshall T. Rose <notifications@github.com<mailto:notifications@github.com>> wrote:


https://github.com/homespun/homebridge-platform-ring-video-doorbell/blob/master/01.png<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhomespun%2Fhomebridge-platform-ring-video-doorbell%2Fblob%2Fmaster%2F01.png&data=02%7C01%7C%7C51cbd057e66b438e334c08d60e763538%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636712298190847566&sdata=ikpBp%2BLRnn6stg0gCZVVk6jsoBnpCvDej1MXH8Wav78%3D&reserved=0> shows what i see in elgato eve and there are two characteristics there... as to why you're not seeing both, i don't know.

**Comment by mrose17** [comment]
Excellent!

**Comment by Hucksleyy91** [comment]
I would love for the button to show like the motion sensor as it’s own accessory in the home app 
Then I could set it to sent me a notification and put it in the same room as a camera and lock until someone gets camera input working :) also 2 way audio is on the list :D

**Comment by Hucksleyy91** [comment]
I was only because there is no button in the home app for doorbell which is what I want, setting motion to true only makes the motion button in home app activate which I want to use for different automations

**Comment by mrose17** [comment]
@Hucksleyy91 - let me make sure i'm on the same page:

the "ask" is for a second motion detector that triggers when the doorbell rings.  is that a fair summary? if so, please create a new issue; if not, please create a new issue explaining what you'd like... thanks!

**Comment by Hucksleyy91** [comment]
Yes a second motion detector for doorbell I will create a new issue :) 
Thanks!
