### ISSUE TITLE
Motion sensor for doorbell button in home app

### ISSUE THREAD

**Issue by Hucksleyy91** [homespun/homebridge-platform-ring-video-doorbell#48]
Would be nice to have a button in home app for doorbell button like a motion sensor, I would like to use the notification setting in home app to notify me of button press :)

**Comment by mattcorey** [comment]
It's relatively straight forward to setup a StatelessProgrammableSwitch in raw HAP-NodeJS - I assume the same could be done here

**Comment by mrose17** [comment]
the plugin already creates a doorbell service with a programmable switch event.

@Hucksleyy91 - can you remind me why this isn't enough? thabnks!

**Comment by Hucksleyy91** [comment]
@mrose17 - It’s not available in the home app, I would like to set “allow notification” on the ring doorbell button so I can see when it rings and I’m not home.

Currently only motion button is available in home app 
I have that set to send me a notification when I’m not home
I would like to set a doorbell button press to always send me notifications even if I’m home or away. :) I can’t use the eve app for this,

**Comment by mattcorey** [comment]
I agree with @Hucksleyy91 -- there are definitely things that Eve will do that the Home App won't allow, but I don't think this should be one of them.

It also presents all three button 'actions' to Homekit (as seen through Eve) -- Single Press, Double Press and Long Press, even though it will trigger only one of those.  Honoring the configuration, or even just tying it to Single Press would be a nice refinement

**Comment by mrose17** [comment]
@mattcorey - when you push the button on the doorbell, the ring api doesn't report the kind of press. a bug in earlier versions of this plugin always reported a press as a double-press. that got fixed to report a single-press, and an option was added to `config.json` so that folks who relied on the old behavior (like @Hucksleyy91) could just add one line to their config.json file and not have to change any exiting triggers.

homekit will generate iOS notifications for only "motion detected" and "contact open". (if someone knows of  others, please let me know!) so if you want an iOS notification, i'd have to add a contact service.

try `npm install -g homebridge-platform-ring-video-doorbell` and see that does what you want...  it should create a contact sensor and you should be able to go to the home app in order to turn on notifications for it.  btw: i can't test it myself (i'm on travel...)

**Comment by mattcorey** [comment]
Backward compatibility is a good point, I will certainly concede that - I still don’t believe it needs to expose all three button states to HomeKit, though.  

I may have some time to put a prototype together this weekend, and will open a Pull Request if I’m able to.

**Comment by Hucksleyy91** [comment]
Agreed @mattcorey it only needs 1 button as long as I can name it “doorbell button”
And turn on notifications using the home app 
@mrose a “contact open” would be good if it has the same options for notifications as the motion sensor option eg time/people options, 
A button would be better but as HomeKit notifications show up in the current format 
SENSOR TYPE/ROOM//DIVICE NAME
Eg “motion detected” by “front door” “Ring motion”
Also Eg
“Button pressed” by “front door” “ring button”

That way I get the ability to add my own camera with 2 way audio eg Arlo baby in the same HomeKit room as well as a Smart lock eg August smart lock as well as a front door light that will come on from motion or button pressed events

**Comment by mrose17** [comment]
@mattcorey - with respect to doorbells, these are defined in homekit as https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2862 ... note that the button is modeled as a programmable switch event, which has three states for button presses.  A new doorbell model may be defined with a read-only single press (off/on), but then eve will give you the choice of triggering on "on" and "off" (and "off" will be the default). so i'd say that what's there now, where the default is "single press" is "best"...

**Comment by mrose17** [comment]
@Hucksleyy91 - both motion detectors and contact sensors get the same "first class" treatment from the home app with respect to applications. the only customization is going to be the name. It's going to say "Closed" or "Open" not "Silent" or "Ringing". that's what you'll see with the current release.

**Comment by mrose17** [comment]
brief update: if you want to see a contact sensor, your option is: 

        "ringing"   : { "event": "single", "contact": true }

`"contact"` used to be `"notifications"` ...

**Comment by mattcorey** [comment]
Interestingly, I _do_ get notifications for both motion and presses.  I _assume_ this is because it’s configured as a doorbell - the only configuration in the Home App I’ve done is to turn on notifications for the Motion control.

It still doesn’t allow me to configure automations based on presses (through Home), but if notifications is all you need, that might be sufficient.

**Comment by Hucksleyy91** [comment]
I’m still not seeing a button in the home app,
Also after updating I don’t see the battery in the eve app either

**Comment by Hucksleyy91** [comment]
Doorbell 1 

firmwareRevision: 'Up to Date' }
  serialNumber: '1004181',
  model: 'doorbell',
  manufacturer: 'Bot Home Automation, Inc.',
  name: 'HUX HOUSE DOORBELL',
[2018-9-14 19:05:01] [ring Doorbell] attachAccessory { uuid: 'ac081bf6-43ca-472e-a0e6-e9602604c3d7',
!!! name=HUX HOUSE DOORBELL kind=doorbell model=doorbell types=["battery_level","battery_low","ringing","motion_detected"] notices={"alerts":{"connection":"online","rssi":"low"},"battery_life":"95"}



 {
      "username" : "my username :)",
      "password" : "my password :)",
      "options" : {
        "retries" : 5,
        "ttl" : 5,
        "verboseP" : false
      },
      "ringing" : {
        "contact" : true,
        "motion" : true,
        "event" : "single"
      },
      "name" : "ring Doorbell",
      "platform" : "ring-video-doorbell"
    }

**Comment by mrose17** [comment]
@Hucksleyy91 - this is what I see without the ringing line (I'm on the road).
![d33dc205-c044-40a2-a04d-a09f19167def](https://user-images.githubusercontent.com/400552/45552461-ee3d5680-b828-11e8-9251-1df958eee0a2.jpeg)

What do you see?

**Comment by Hucksleyy91** [comment]
Since updating from I think version 0.10.0 or even earlier the battery percent doesn’t show correctly it states 0% but when starting up homebridge it can see it’s not at 0%.  It shows 86%

Also THANKS that worked it shows in the home app I’m yet to test it 

also if you use "contact" : true it shows in the eve app always saying yes when there is no press I’m yet to test to see if it goes to “no” when I press doorbell button. 

Thanks for your support this is becoming a great plugin

**Comment by mrose17** [comment]
the home app reports when the contact sensor goes from CLOSED to OPEN; on the eve app, the terms of YES and NO. in other words, when the doorbell rings home says OPEN and eve says NO.  OPEN or NO for a contact sensor indicates something to pay attention to.

in other words, i think it's working the way it is supposed to.

i found the battery reporting problem and fixed it in `homebridge-platform-ring-video-doorbell@0.11.7`
