### ISSUE TITLE
Not showing up in IOS Home or eve app

### ISSUE THREAD

**Issue by QuinnDD** [homespun/homebridge-platform-ring-video-doorbell#49]
Hi, 

I managed to install the plugin perfectly. The log says it launched and when I press the ring the log shows me that the ring is pressed. 

But I can’t see any motion detector or trigger switch in my Home app or eve app....

Any help? Thnx !

**Comment by mrose17** [comment]
please take a look at the README -- https://github.com/homespun/homebridge-platform-ring-video-doorbell#homekit-appearance -- to see what you should see!

**Comment by QuinnDD** [comment]
That is the problem they don't show up......

**Comment by mrose17** [comment]
in that case, try this: stop homebridge; and then start homebridge like this

        DEBUG=ring-video-doorbell export DEBUG homebridge

look for lines like this

          ring-video-doorbell connecting +0ms

(the ones that start with `ring-video-doorbell`) and see what they say.

**Comment by QuinnDD** [comment]
ring-video-doorbell connecting +0ms
[2018-9-7 15:02:11] [Doorbell] didFinishLaunching
[2018-9-7 15:02:11] Homebridge is running on port XXXXX.
  ring-video-doorbell connected +3s

this is the output

**Comment by mrose17** [comment]
nothing else? that is very odd. start with

        npm upgrade -g homebridge-platform-ring-video-doorbell

and the stop homebridge and re-run the `DEBUG=...` command above, and then please report back what you see... thanks!

**Comment by QuinnDD** [comment]
ring-video-doorbell connecting +0ms
[2018-9-7 15:12:18] [Doorbell] didFinishLaunching
[2018-9-7 15:12:18] Homebridge is running on port XXXXX.
  ring-video-doorbell connected [ 'doorbots',
  'authorized_doorbots',
  'chimes',
  'stickup_cams',
  'base_stations' ] +3s

output above

**Comment by QuinnDD** [comment]
ring-video-doorbell connecting +0ms
[2018-9-7 15:25:22] [Doorbell] didFinishLaunching
[2018-9-7 15:25:22] Homebridge is running on port XXXXX.
  ring-video-doorbell connected doorbots=0 authorized_doorbots=1 chimes=0 stickup_cams=0 base_stations=0 +2s

on 0.10.2 now

**Comment by QuinnDD** [comment]
still not showing up ?

**Comment by mrose17** [comment]
sorry, github got ahead of npm. rinse and repeat the steps above to get 0.10.3

**Comment by QuinnDD** [comment]
Working ! Great work thnx !

**Comment by QuinnDD** [comment]
but I have no trigger only a motion ?

**Comment by mrose17** [comment]
You can go to the home app, find the motion sensor, and enable notifications...

No camera support yet.
