### ISSUE TITLE
Options?

### ISSUE THREAD

**Issue by jbsolutios** [homespun/homebridge-platform-ring-video-doorbell#5]
Could you tell me what the "options" section is please?

, "options"   : { "ttl": 4, "verboseP" : false }

Many thanks

**Comment by mrose17** [comment]
`ttl` indicates how often the plugin should poll the cloud for updates (i'd prefer a push system, but that doesn't seem possible at present). the ring app uses 5 seconds; 4 seems to work "better" for the plugin.

`verboseP` indicates whether verbose logging should be enabled in the plugin; that's sometimes helpful when debugging an issue.

**Comment by ecregister** [comment]
Tech savy, coding newbie, need help. I've got homebridge working with a half dozen plugins, including this one perfectly.... except, for the life off me can get the ring motion sensor to read motion for an automation in HomeKit (it read's, because the ring app notifies me of the movement), but does not show "Active" ever on iOS device to trigger the automation (porch light). I've have played with option "ttl" at 2,4,6 with. no luck.

**Comment by mrose17** [comment]
@ecregister - hi. it is very odd, some days the plugin bats about .750 (3 in 4) in alerting me; other days .000 ... i have some theories, but nothing really actionable, as to why that is.

the API is based on someone else's unofficial reverse engineering, so there may be some nuance that's being missed in the protocol interaction.

**Comment by fserruto** [comment]
That's my experience, not as reliable as I'd like for motion detected portch light activation. Often works the first time motion is detected after a period of inactivity, but not subsequent times...

**Comment by ecregister** [comment]
It worked one time, randomly. Then never again. But no crashes or error messages, I still get the ring notification, and everything else in order.... I didn't change any code, and conf is in order..... can't figure it out.

**Comment by mrose17** [comment]
as far as i can tell, the `"motion: true"` events aren't returned  during polling unless the plugin gets there first. i find it puzzling as well. i am told that the next generation of ring video doorbell will have native homekit, which is great, but not for me... my ring is not near house power and that's a requirement for the new model, apparently.
