### ISSUE TITLE
Stick-up can showing up as floodlight

### ISSUE THREAD

**Issue by Cardo1** [homespun/homebridge-platform-ring-video-doorbell#50]
Now that we've got the lights working (Well done!) there's just one other thing...

I have an original Stick-up cam, which doesn't have a light.  However, this shows up as a Floodlight in Homekit.  Would it be possible to remove this as an accessory for this type of camera?

Cheers.

**Comment by mrose17** [comment]
run homebridge and after it starts look for a line that looks like:

         [2018-9-11 06:06:39] [Doorbell] attachAccessory { uuid: '92907fb2-45ea-4e19-b2c0-52cd0ac1c997',
          name: 'Backyard',
          manufacturer: 'Bot Home Automation, Inc.',
          model: 'hp_cam_v1',
         serialNumber: '4073800',
         firmwareRevision: 'Up to Date' }

and tell me what the `model` is for your stickup-cam

**Comment by Cardo1** [comment]
It is a...
!!! name=Garage kind=camera model=stickup_cam types=["floodlight","motion_detected"] notices={"alerts":{"connection":"online"},"battery_life":"100"}
[9/11/2018, 6:35:22 PM] [Doorbell] attachAccessory { uuid: 'blah',
  name: 'Garage',
  manufacturer: 'Bot Home Automation, Inc.',
  model: 'stickup_cam',
  serialNumber: 'blah',
  firmwareRevision: 'Up to Date' }

stickup_cam!

**Comment by mrose17** [comment]
try npm install -g homebridge-platform-ring-video-doorbell to get version 0.11.1 that should address this problem!

**Comment by Cardo1** [comment]
Fixed!  Thanks!
