### ISSUE TITLE
install issue on windows 10

### ISSUE THREAD

**Issue by erichter2018** [homespun/homebridge-platform-ring-video-doorbell#51]
getting the following error when trying to install... any thoughts?

-------------------------------------

C:\WINDOWS\system32>npm install -g homebridge-platform-ring-video-doorbell

> arp-a@0.5.2 install C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules\arp-a
> node-gyp rebuild

C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules\arp-a>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  win_delay_load_hook.cc
  Generating code
  Finished generating code
  macos.vcxproj -> C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules
  \arp-a\build\Release\\macos.node
  macos.vcxproj -> C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules
  \arp-a\build\Release\macos.pdb (Full PDB)

> socketwatcher@0.3.0 install C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules\socketwatcher
> node-gyp rebuild

C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules\socketwatcher>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  socket_watcher.cpp
  win_delay_load_hook.cc
..\socket_watcher.cpp(77): warning C4996: 'Nan::MakeCallback': was declared deprecated [C:\Users\erich\AppData\Roaming\
npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules\socketwatcher\build\socketwatcher.vcxproj]
  C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules\nan\nan.h(958):
  note: see declaration of 'Nan::MakeCallback'
     Creating library C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modu
  les\socketwatcher\build\Release\socketwatcher.lib and object C:\Users\erich\AppData\Roaming\npm\node_modules\homebrid
  ge-platform-ring-video-doorbell\node_modules\socketwatcher\build\Release\socketwatcher.exp
  Generating code
  Finished generating code
  socketwatcher.vcxproj -> C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node
  _modules\socketwatcher\build\Release\\socketwatcher.node
  socketwatcher.vcxproj -> C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node
  _modules\socketwatcher\build\Release\socketwatcher.pdb (Full PDB)

> pcap@2.1.0 install C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules\pcap
> node-gyp rebuild

C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules\pcap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  pcap_binding.cc
  pcap_session.cc
  win_delay_load_hook.cc
..\pcap_binding.cc(2): fatal error C1083: Cannot open include file: 'pcap/pcap.h': No such file or directory [C:\Users\
erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules\pcap\build\pcap_binding.vcx
proj]
..\pcap_session.cc(2): fatal error C1083: Cannot open include file: 'pcap/pcap.h': No such file or directory [C:\Users\
erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules\pcap\build\pcap_binding.vcx
proj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\erich\AppData\Roaming\npm\node_modules\homebridge-platform-ring-video-doorbell\node_modules\pcap
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcap@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcap@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\erich\AppData\Roaming\npm-cache\_logs\2018-09-11T07_53_07_351Z-debug.log

**Comment by mrose17** [comment]
try `npm install -g homebridge-platform-ring-video-doorbell` to get version `0.11.0` that should address this problem!
