### ISSUE TITLE
lpd_v2

### ISSUE THREAD

**Issue by erichter2018** [homespun/homebridge-platform-ring-video-doorbell#52]
Is it normal to get the following error message when homebridge initializes?

[2018-9-12 01:33:06] [Front Door] doorbell { err: 'no entry for lpd_v2' }

**Comment by mrose17** [comment]
sort of... it's really a note to the developer (me). what model of ring doorbell do you have: 

- video doorbell
- video doorbell 2
- video doorbell pro
- video doorbell elite

and is it using batteries or house power?

thanks!

**Comment by erichter2018** [comment]
It’s video doorbell pro, hard wired.

**Comment by mrose17** [comment]
thanks. OK, do

        npm update -g homebridge-platform-ring-video-doorbell

and you'll get version `0.11.4` that will remove the warning... thanks!
