### ISSUE TITLE
Log keeps repeating chime connection necessarily

### ISSUE THREAD

**Issue by mkormendy** [homespun/homebridge-platform-ring-video-doorbell#53]
I keep seeing this response repeated in the logs:

`!!! name=Ring Bell kind=chime model=chime types=["ringing"] notices={"alerts":{"connection":"online"}}`

I don't think there is a setting to turn it off, but I've simply comment out lines 218-221 because that's what is producing it.
Can we either have some logic added to recognize chime bells for this log event? Or at least a log_level setting for the platform in the homebridge config for the Ring platform?

**Comment by mrose17** [comment]
Try `npm update -g homebridge-platform-ring-video-doorbell` and the "problem" will go away!
