### ISSUE TITLE
could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-a66c9a94': Permission denied

### ISSUE THREAD

**Issue by ronzelver** [homespun/homebridge-platform-ring-video-doorbell#54]
I'm still getting this error when I try to install the plugin with the following command:

`sudo npm install -g --unsafe-perm homebridge-platform-ring-video-doorbell`
`sudo apt-get install libpcap-dev` is correctly installed
I also set the permissions on the /root/.npm folder temporarily to 0777, but still the same error?!

`26 silly fetchPackageMetaData error for hap-nodejs-community-types@git+https://github.com/homespun/hap-nodejs-community-types.git Command failed: /usr/bin/git clone -q https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-a66c9a94
26 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-a66c9a94': Permission denied
27 verbose stack Error: Command failed: /usr/bin/git clone -q https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-a66c9a94
27 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-a66c9a94': Permission denied
27 verbose stack
27 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
27 verbose stack     at emitTwo (events.js:126:13)
27 verbose stack     at ChildProcess.emit (events.js:214:7)
27 verbose stack     at maybeClose (internal/child_process.js:925:16)
27 verbose stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
27 verbose stack     at emitOne (events.js:116:13)
27 verbose stack     at Socket.emit (events.js:211:7)
27 verbose stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
28 verbose cwd /var
29 verbose Linux 4.9.59-v7+
30 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-platform-ring-video-doorbell"
31 verbose node v8.9.4
32 verbose npm  v5.6.0
33 error code 128
34 error Command failed: /usr/bin/git clone -q https://github.com/homespun/hap-nodejs-community-types.git /root/.npm/_cacache/tmp/git-clone-a66c9a94
34 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-a66c9a94': Permission denied`

**Comment by Hucksleyy91** [comment]
You need to do “sudo -s” first then run the same command :)

**Comment by ronzelver** [comment]
Thanks, that did the trick!

**Comment by aryeharmon** [comment]
“sudo -s” worked' what does it do? why does it work?

**Comment by baerbock** [comment]
@ronzelver `sudo -s` hasn't worked for me.

**Comment by ronzelver** [comment]
@baerbock did you also use the original command after entering 'sudo -s'?

**Comment by arturskeeled** [comment]
`sudo -s`
`sudo npm i`
fixed it for me, would love to know why

**Comment by ronzelver** [comment]
The -s flag makes sudo to start a new command shell as root instead of changing to root in the current she'll.

**Comment by pankaj-garg** [comment]
sudo -s worked!
