### ISSUE TITLE
Ring Motion state does not update from triggered unless you open/close the home app.

### ISSUE THREAD

**Issue by Hucksleyy91** [homespun/homebridge-platform-ring-video-doorbell#56]
I have to open close the home app to get my ring motion button to update its state, 
It triggers fine but unless I open/close the home app after it’s triggered it won’t trigger again as it thinks it’s still triggered, the ring doorbell contact sensor has none of these issues

**Comment by mrose17** [comment]
sorry, but that's the way that homekit works. the home app is the thing responsible for notifications, none of the other apps...

**Comment by Hucksleyy91** [comment]
This basically makes the motion sensor unusable as I don’t plan on opening the home app after everytime motion has been triggered, ill just disable the motion notification till it works itself out. Unless you change the motion sensor to a contact sensor like the ring doorbell has as it’s working perfectly

**Comment by mrose17** [comment]
interesting. try out the current version, 0.12.0, i think it addresses it... and you may see the doorbell actually ringing!

**Comment by Hucksleyy91** [comment]
The doorbell is already ringing in the current version 0.11.7 :) only issue is the motion sensor staying triggered until you close/open the home app for it to check the sensor state for which it then will go back to “no motion” 

It activates fine but stays on until you open /close the home app it will not check the status and go back to “no motion” on its own

**Comment by mrose17** [comment]
well, i'm using the latest and i can't reproduce this. not sure why!?!

**Comment by Hucksleyy91** [comment]
I’m on version 11.7 With the issue I will update and try this and let you know what happens

**Comment by darksoul1286** [comment]
I was on 11.7 and I updated to the latest version and I am also have the same issue where it will detect motion but won't update the motion status unless I open the home app. Currently I have it set so if there is motion, certain lights would turn on. Once motion is cleared, turn off lights. The problem is it never turn off the light because motion is never cleared until I open the home app.
