### ISSUE TITLE
notification with snapshot

### ISSUE THREAD

**Issue by henkied** [homespun/homebridge-platform-ring-video-doorbell#58]
Hello,

Is it possible to receive a home kit notification with a snapshot when the doorbell rings?

**Comment by mrose17** [comment]
a notification, yes. you need to turn on notifications for the device using apple's `Home` app... a snapshot... not yet: this is what https://github.com/homespun/homebridge-platform-ring-video-doorbell/issues/25 is all about.

**Comment by henkied** [comment]
Strange. I have a netatmo camera here. When there is a bell, I get a snapshot with a notification "There is ringing". I have not set anything for this.

**Comment by mrose17** [comment]
@henkied - that is the _magic_ of homekit!
