### ISSUE TITLE
Motion sensor alerts

### ISSUE THREAD

**Issue by bgalp** [homespun/homebridge-platform-ring-video-doorbell#59]
After days of testing this plugin, it appears that the motion alerts reported by the HomeKit are spotty and inconsistent while Ring motion notifications pop up on every occurrence. Am running all latest os on raspberry e b+

**Comment by gilbert76** [comment]
I have similar problem. After restart Homebridge the motion alerts are reported for a small time. For example 10 min. . After them I don’t get more motion alerts over HomeKit.

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
