### ISSUE TITLE
What CAN i do with this plugin?

### ISSUE THREAD

**Issue by sohnkarlsruhe** [homespun/homebridge-platform-ring-video-doorbell#6]
Video in HomeKit, HomeKit alert when someone push the button?

**Comment by mrose17** [comment]
at present, there is no video support; however, you will get notifications for both button-push and motion.

**Comment by sohnkarlsruhe** [comment]
do you work on this feature or it's not possible?

**Comment by mrose17** [comment]
it's possible, but i don't have the time to work on it right now...

**Comment by sohnkarlsruhe** [comment]
ok. it would be great if you can do this in the near future. This is a great feature! If you accept a tip let me know.

**Comment by mrose17** [comment]
i hope to have the time this spring. no tips accepted, but thanks!

**Comment by sohnkarlsruhe** [comment]
Did you know how i can access video from the cam? With homebridge ip-camera Plugin ?

**Comment by mrose17** [comment]
short answer: no plans at this time. i am looking for a volunteer to do the work. they need to have experience with SIP, which is a bit of an issue...

**Comment by barkerja** [comment]
If you use https://github.com/KhaosT/homebridge-camera-ffmpeg and place the accessory in the same "room" as the ring doorbell, HomeKit will take care of marrying the two as one "seamless" device for actions like a doorbell trigger.

It's a decent workaround until we get better homebridge support and/or ring and other accessories become HomeKit -enabled.

**Comment by rjmcfadd** [comment]
@barkerja What settings do you use for Ring in the camera-ffmpeg plugin?

**Comment by kapps7** [comment]
I can't find any rtsp support for Ring so how would you use it the ffmpeg plugin

**Comment by jocamero** [comment]
@barkerja can you please go into detail on how you got the video feed from Ring into homebridge?  Thanks!
