### ISSUE TITLE
"Motion Detector" Notifications - no thumbnail / no snapshot

### ISSUE THREAD

**Issue by nicoh88** [homespun/homebridge-platform-ring-video-doorbell#60]
Hi @homespun,

thanks for your homebridge-plugin! 👍 

In your [ReadMe](https://github.com/homespun/homebridge-platform-ring-video-doorbell#motion-detector-notifications) is a screenshot of a motion alert with a preview image. Is that still up to date, that is, should a preview image still be displayed?

Unfortunately no thumbnail is displayed for me? 😢 
What's going on there?

I have a Ring video Doorbell Pro (lpd_v2).

Best regards
Nico

![_homebridge-ring-no-thumbnail](https://user-images.githubusercontent.com/264264/48703213-51fe4a00-ebf3-11e8-98cc-ec5ca3d8d197.png)

**Comment by ifeign** [comment]
https://github.com/homespun/homebridge-platform-ring-video-doorbell/issues/58

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
