### ISSUE TITLE
Characteristic.MotionDetected always on true

### ISSUE THREAD

**Issue by nicoh88** [homespun/homebridge-platform-ring-video-doorbell#61]
Hi @homespun,

thanks for your homebridge-plugin! 👍 

you have a little bug in your programming. Ok, what is called **bug**, it is a singularity of HomeKit. 

When the inofficel Ring API reports a motion, you sets the `Characteristic.MotionDetected` to `true` in HomeKit - but you never changes that state to `false`.

That's why all users of your plugin will only get a notification when a move is detected - see #59. In any case, if Apple Home App has not killed or the room is changed and the status is queried again - so the status always stays on `MotionDetected`.

After X seconds, you should also set a `Characteristic.MotionDetected` to `false`.

Thank you und best regards
Nico

![_homebridge-ring-motion-no-motion-until-30seconds](https://user-images.githubusercontent.com/264264/48704189-36e10980-ebf6-11e8-9e5d-9b1e332a7126.png)

**Comment by Hucksleyy91** [comment]
I’m having this same issue

**Comment by craigdent** [comment]
Yeah me too. Kind of annoying haha

**Comment by craigdent** [comment]
Any updates on this or a fix to reset itself going from motion detected all the time?

Having to open the app is a bit annoying and sometimes forget

**Comment by isalkind** [comment]
I have a pull request that resolves this issue. You can find the updated code in: https://github.com/isalkind/homebridge-platform-ring-video-doorbell

**Comment by craigdent** [comment]
Thanks isalkind!
How can I update to your pull request?

**Comment by isalkind** [comment]
Easiest would be to wait for the PR to be accepted and simply update to the latest. Alternatively, you should be able to do `npm install https://github.com/isalkind/homebridge-platform-ring-video-doorbell.git` using any additional npm flags appropriate to your installation.

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
