### ISSUE TITLE
Ring Spotlight Cam adds a Floodlight device which doesn't work

### ISSUE THREAD

**Issue by PicoMitchell** [homespun/homebridge-platform-ring-video-doorbell#62]
I just got this homebridge plugin installed and it's working great for integrating the Ring motion detection with HomeKit Automation, thanks!

But, I am seeing "Floodlight" devices for my two Ring **Spotlight** Cams. And, these Floodlight devices default to On and don't turn on or off the actual light on the spotlight cams.

Would it be possible to make them proper "Spotlight" devices that actually turn on and off the spotlight, or at least have the plugin not add the non-functional "Floodlight" devices for the Spotlight Cams.

Please let me know if there's any diagnostic info you need from me.

Thanks!

**Comment by gallarda** [comment]
I have a Spotlight Cam and a Floodlight Cam.  I can control the light on both, but for some reason the Spotlight Cam light always shows as "on" even though it is turned off.  I need to toggle it off and then on to turn off the light.

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
