### ISSUE TITLE
getaddrinfo EAI_AGAIN

### ISSUE THREAD

**Issue by scheng123** [homespun/homebridge-platform-ring-video-doorbell#63]
I'm having a lot of errors in the log that keeps saying:
`refresh2 { username: 'MYEMAIL',
  diagnostic: 'Error: getaddrinfo EAI_AGAIN api.ring.com:443' }`

My network seems ok, and my research says there's something wrong in the DNS lookup but I don't see any errors with that. Any help will be highly appreciated

**Comment by focher** [comment]
Experiencing the same error.

diagnostic: 'Error: getaddrinfo EAI_AGAIN api.ring.com api.ring.com:443'

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
