### ISSUE TITLE
Doorbell switch not showing in home or eve

### ISSUE THREAD

**Issue by jcapayne** [homespun/homebridge-platform-ring-video-doorbell#64]
I see others mention the motion sensor not showing up, but I have motion but no "doorbell" or switch.

I do see: [1/12/2019, 3:39:53 AM] [Doorbell] doorbell { err: 'no entry for doorbell_v3' }  which seems odd... right after that I see the motion sensor with type of doorbell_v3...

**Comment by jcapayne** [comment]
I got a notification from home when the doorbell was pushed, but I only see "motion" in triggers

**Comment by joelvanormelingen** [comment]
HI i have the same, got the motion sensor but no switch showing. did you solve it?

**Comment by Kroellie** [comment]
I have motion sensor, and motion notification (tip: turn notification sensor on in homekit), but I have no sensor "doorbell has been pressed"... I want to flash a light in the house for example on doorbell, but I cannot create a trigger if I don't have an origin...

**Comment by joelvanormelingen** [comment]
There’s an ifft for that press>light on.

**Comment by Kroellie** [comment]
That's nice to know, but somehow I feel this is not sufficient for my needs... I simply want a triggerable sensor, that should be the case right, or do I understand the concept wrong?

**Comment by joelvanormelingen** [comment]
You understand the concept correct, but to flash light when bell is pressed the ifttt will do, would be nice to have it all in 1 place that’s the main reason why were are on homebridge anyway...

**Comment by Kroellie** [comment]
new learning: apparently I can create an automation in eve, and see the rule being created in homekit automation... I cannot adjust the accessory / scene from homekit automation after that... only in eve.

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
