### ISSUE TITLE
Ring HomeKit Alerts

### ISSUE THREAD

**Issue by adavison007** [homespun/homebridge-platform-ring-video-doorbell#66]
When the door bell rings homekit shows a notification, even if I turn off don't show notifications for my doorbell it still shows the ring alert when doorbell pressed... this is fine for me, but the other 7 people I have invited to my home don't like it... is there a way to stop ring iOS homekit alerts when the doorbell is pressed...

**Comment by Hucksleyy91** [comment]
Install the ring add on for home assistant, it has a button for rings instead of a notification you cannot turn off

**Comment by adavison007** [comment]
> Install the ring add on for home assistant, it has a button for rings instead of a notification you cannot turn off

Thanks, not sure what you mean, do you have a link for the plugin? also is this to replace this plugin, or as well as this plugin?

Thanks in advance

**Comment by Hucksleyy91** [comment]
This plugin works on homebridge, but there is another one called home assistant, and it has a ring add on also, that does not have the ring notification you can’t turn off

**Comment by adavison007** [comment]
Thankyou

Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 7 Mar 2019, at 22:47, Hucksleyy91 <notifications@github.com> wrote:

This plugin works on homebridge, but there is another one called home assistant, and it has a ring add on also, that does not have the ring notification you can’t turn off

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
