### ISSUE TITLE
Error: API returned Status Code 403

### ISSUE THREAD

**Issue by rgerr** [homespun/homebridge-platform-ring-video-doorbell#68]
Getting this error when starting Homebridge:

[Doorbell] refresh1 { username: 'xxxx@xxxxxx.com',
  diagnostic: 'Error: API returned Status Code 403' }

Username and password are correct. Also tried restarting Homebridge and rebooting the entire server. No success.

**Comment by gilbert76** [comment]
Yes, i can confirm this issue, i have the same Problem.

**Comment by Crox77** [comment]
Same issue here, stared this morning only

**Comment by vqv** [comment]
Same issue:
`[3/8/2019, 1:10:07 PM] [Doorbell] refresh1 { username: 'xxx@xxx',
  diagnostic: 'Error: API returned Status Code 403' }
`

**Comment by isalkind** [comment]
Same here. Issue started about 5pm PST yesterday. Based on the fact the the official Ring app is still functional, my first guess would be that the Ring API has been updated.

**Comment by Crox77** [comment]
Everything started working ok this morning, no more error messages and Homekit notifications started again

**Comment by 400HPMustang** [comment]
I'm getting the same error as of this morning

```
[2019-3-12 08:19:28] [Front Door] refresh2 { username: '********@*****.com',
  diagnostic: 'Error: getaddrinfo ENOENT api.ring.com:443' }
```

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
