### ISSUE TITLE
Error: getaddrinfo

### ISSUE THREAD

**Issue by 400HPMustang** [homespun/homebridge-platform-ring-video-doorbell#69]
I'm getting the following in my console output

```
[2019-3-12 08:19:28] [Front Door] refresh2 { username: '********@*****.com',
  diagnostic: 'Error: getaddrinfo ENOENT api.ring.com:443' }
```

It seems since I'm getting that in my console Homebridge is no longer responding in HomeKit as well.

**Comment by ashman247** [comment]
I'm getting the same error too, and is causing the rest of Homebridge to become non-responsive in HomeKit.

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
