### ISSUE TITLE
_roundTrip error - username: undefined

### ISSUE THREAD

**Issue by fserruto** [homespun/homebridge-platform-ring-video-doorbell#7]
I'm receiving a similar error to one of the closed issues "get roundtrip error", yet I'm certain I've entered the correct username and password. It appears my username is undefined, although I've entered my email address in config.json...

[2/3/2017, 10:32:21 AM] [homebridge-platform-ring-video-doorbell.ring-video-doorbell] _roundTrip error: HTTP response 401
[2/3/2017, 10:32:21 AM] [homebridge-platform-ring-video-doorbell.ring-video-doorbell] login { username: undefined }

Any thoughts?

**Comment by mrose17** [comment]
here is what my config.json looks like:

        {
          "bridge": {
            "name": "homebridge",
            "username": "88:53:95:2D:69:FD",
            "port": 51826,
            "pin": "031-45-154"
          },
          "description": "",
          "accessories": [
          ],
          "platforms": [
            { "platform"   : "ring-video-doorbell"
            , "name"       : "..."
            , "username"   : "..."
            , "password"   : "..."
            }
          ]
        }

how close is that to yours?

**Comment by fserruto** [comment]
Very similar, although mine has more platforms and accessories.  I'll run through it with a fine-tooth comb over the weekend to see what's wrong

**Comment by mrose17** [comment]
thanks! good luck!

**Comment by fserruto** [comment]
Ok we have success, recreated my config.json and restarted and we're in business.  Can't point it to a specific issue because it was all copy and paste, but it's working!

**Comment by mrose17** [comment]
excellent! good luck!
