### ISSUE TITLE
Camera preview

### ISSUE THREAD

**Issue by rgerr** [homespun/homebridge-platform-ring-video-doorbell#70]
Hi,

Trying to integrate the ring doorbell snapshots with Homebridge. So that I can create a dummy camera that only updates the still image. I found the following in the python-ring:

https://github.com/tchellomello/python-ring-doorbell/pull/108

Looks like it is now possible to download the image so that the above could be possible. Any way to integrate this in the plug-in, or creating a still image source link?

**Comment by Hucksleyy91** [comment]
Home assistant has a plugin for ring that has the last video recorded also shows a snapshot hopefully it’s helpful 
looking forward to updates :)

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
