### ISSUE TITLE
Customizing Floodlights and upcoming Smart lights. Changing the lights from a light to a switch

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [homespun/homebridge-platform-ring-video-doorbell#71]
It would be nice if you could customize the smart lights to either show up as a light switch or a light, like the flood does now.

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
