### ISSUE TITLE
Ring Smart Lighting Support

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [homespun/homebridge-platform-ring-video-doorbell#72]
Just wondering if this plugin will gain the new smart lighting support.

**Comment by dgreif** [comment]
For anyone interested in Ring Smart Lights, I have them integrated in my `homebridge-ring-alarm` plugin https://github.com/dgreif/ring-alarm/tree/master/homebridge

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
