### ISSUE TITLE
Can't install plugin 

### ISSUE THREAD

**Issue by dmatchx** [homespun/homebridge-platform-ring-video-doorbell#75]
I get this msg

CMD: sudo -E -n npm --no-update-notifier install --unsafe-perm homebridge-platform-ring-video-doorbell@latest

npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hoobs/.npm/_logs/2019-06-14T23_10_07_318Z-debug.log

Command failed. Please review log for details.

here is some snip from the log
8 silly pacote tag manifest for homebridge-platform-ring-video-doorbell@latest fetched in 627ms
9 timing stage:loadCurrentTree Completed in 695ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 2ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 12ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule homebridge-platform-ring-video-doorbell@0.12.1 checking installable status
17 silly fetchPackageMetaData error for hap-nodejs-community-types@git+https://github.com/homespun/hap-nodejs-community-types.git Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 http fetch GET 200 https://registry.npmjs.org/doorbot 272ms (from cache)
19 http fetch GET 200 https://registry.npmjs.org/underscore 232ms (from cache)
20 silly pacote range manifest for doorbot@^5.4.0 fetched in 298ms
21 silly resolveWithNewModule doorbot@5.4.0 checking installable status
22 silly pacote version manifest for underscore@1.8.3 fetched in 258ms
23 silly resolveWithNewModule underscore@1.8.3 checking installable status
24 http fetch GET 304 https://registry.npmjs.org/debug 349ms (from cache)
25 silly pacote range manifest for debug@~2.6.9 fetched in 400ms
26 silly resolveWithNewModule debug@2.6.9 checking installable status
27 http fetch GET 304 https://registry.npmjs.org/homespun-utilities 395ms (from cache)
28 silly pacote version manifest for homespun-utilities@0.3.1 fetched in 405ms
29 silly resolveWithNewModule homespun-utilities@0.3.1 checking installable status
30 timing stage:rollbackFailedOptional Completed in 4ms
31 timing stage:runTopLevelLifecycles Completed in 1222ms
32 verbose stack Error: spawn git ENOENT
32 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
32 verbose stack     at onErrorNT (internal/child_process.js:415:16)
32 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
33 verbose cwd /usr/local/lib
34 verbose Linux 4.19.42-v7+
35 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--no-update-notifier" "install" "--unsafe-perm" "homebridge-platform-ring-video-doorbell@latest"
36 verbose node v10.16.0
37 verbose npm  v6.9.0
38 error path git
39 error code ENOENT
40 error errno ENOENT
41 error syscall spawn git
42 error enoent Error while executing:
42 error enoent undefined ls-remote -h -t https://github.com/homespun/hap-nodejs-community-types.git
42 error enoent
42 error enoent
42 error enoent spawn git ENOENT
43 error enoent This is related to npm not being able to find a file.
44 verbose exit [ 1, true ]

**Comment by dmatchx** [comment]
Look like this package is not available anymore

https://www.npmjs.com/package/hap-nodejs-community-types, anyway to get around it?

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
