### ISSUE TITLE
Ring 2FA

### ISSUE THREAD

**Issue by adavison007** [homespun/homebridge-platform-ring-video-doorbell#76]
<img width="1159" alt="Screenshot 2019-06-19 at 20 25 23" src="https://user-images.githubusercontent.com/47482260/59794232-66f9a380-92d0-11e9-8583-6a4cb71c0373.png">
Just turned on Ring 2FA on my app and now the plugin says cannot authenticate?

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
