### ISSUE TITLE
 Mask some Ring devices

### ISSUE THREAD

**Issue by xc99tour** [homespun/homebridge-platform-ring-video-doorbell#77]
We have two ring devices at our home (doorbell and stickup camera in the back porch area) and are “guests” for two other ring doorbells (mother in-law and her neighbor) so we can help them if the have any issues with their ring doorbells.  I would rather not have these two doorbells show up in HomeKit. Not a huge thing, but desirable. Any way or possible plans to configure devices to be ignored by the plugin?  Thanks.

**Comment by mrose17** [comment]
This plugin is now **DEPRECATED**... you will find a _vastly superior_ plugin [here](https://github.com/dgreif/ring/tree/master/homebridge)!
